export const SOURCE='https://openline-revisions-hub.vercel.app/app-screens';
export const FLOWS=[
  {id:'purchase',name:'Purchase & payment',short:'Purchase',description:'From cart to a purchase code, with payment checks along the way.',steps:['cart','delivery','payment','bank','pending','receipt','code']},
  {id:'gift',name:'Give & receive',short:'Gifting',description:'Unlock deliberately. Let the recipient redeem when they are ready.',steps:['code','unlock','gift-ready','gift-received','gift-pending','readiness']},
  {id:'activate',name:'Activate & connect',short:'Activation',description:'Consent, provisioning, QR, phone settings and a clear finish.',steps:['readiness','provisioning','qr','install','settings','connected','profile']},
  {id:'manage',name:'Manage your eSIMs',short:'Manage',description:'A useful everyday workspace for profiles, folders, top-ups and usage.',steps:['profile','label','folders','topup','usage']},
  {id:'support',name:'Find a better connection',short:'Support',description:'Troubleshoot, understand local rules and get a profile review.',steps:['troubleshoot','fair-use','replacement','support']},
  {id:'account',name:'Orders & account',short:'Account',description:'Keep receipts accessible and sensitive account actions deliberate.',steps:['orders','privacy']},
];
const rows=[
  ['cart','Your cart','purchase','Cart, quantity and order summary','Edit quantities, remove or restore an item, and keep totals consistent. Top-up selections return here with the chosen allowance.','Cart lines and quotes must come from the commerce backend. Revalidate totals before payment.'],
  ['delivery','Traveller & receipt','purchase','Delivery details before payment','A focused receipt-email form with a gifting intention, without inventing a shipping address for a digital product.','Validate email on the server; purchasing for someone is not the same as unlocking transfer.'],
  ['payment','Payment methods','purchase','Choose a payment route','Saved card, wallet and redirect options use one selection pattern and one clear total. No real card details are collected here.','Show only PSP methods actually supported by device, currency and country.'],
  ['bank','Bank approval','purchase','Authentication in context','Keep the order visible while authentication happens, with a safe return to payment selection.','Use the PSP’s hosted 3DS flow. Never collect bank login or OTP inside an Openline imitation.'],
  ['pending','Checking payment','purchase','Unknown outcome, without a second charge','A calm pending state with status checking, failure recovery and no duplicate pay button.','Reconcile the original payment intent and webhook. A timeout is not proof of failure or success.'],
  ['receipt','Order receipt','purchase','A useful, detailed receipt','View line items, total, payment method and the purchased code; continue to the order or code rather than forcing activation.','Use server-confirmed paid status, receipt details and actual taxes. The example totals are design fixtures.'],
  ['code','Purchase-code details','gift','A purchase is not an installed eSIM','One place for the code, purchase status and the Activate / Gift / Keep choices. Activated codes no longer offer transfer.','Authenticate the purchaser and return validation, redemption and transfer status without consuming the code.'],
  ['unlock','Unlock for gifting','gift','An explicit transfer decision','Explain owner validation and the risk of anyone with the code redeeming it; require a separate confirmation.','Verify ownership and unused status, record the unlock and preserve the owner-email validation step.'],
  ['gift-ready','Your gift is ready','gift','Share a useful gift message','Copy the unlocked code with clear redemption instructions, without activating it or claiming an email was sent.','The system share route is a separate native implementation. Never expose code-bearing links in analytics.'],
  ['gift-received','Received a gift','gift','Recipient entry and eligibility','Review a gift without starting it, handle a locked code and proceed only when eligible.','Validate gift eligibility atomically again when redeeming. Never disclose sender account details.'],
  ['gift-pending','Waiting for the owner','gift','Pending owner validation','Keep the recipient informed, provide a sender-help message and allow rechecking without bypassing validation.','Only a verified server transition can make a pending gift eligible. No email is sent in this reference.'],
  ['readiness','Ready to start?','activate','Consent before validity begins','A large, off-by-default readiness switch and a concise confirmation before the purchase code is consumed.','Use current Openline rules: checking does not activate; confirmed activation begins validity and ends gifting.'],
  ['provisioning','Creating your eSIM','activate','Provisioning and safe recovery','Progress, retry and success states stay within the same process rather than losing the purchase-code context.','Use an idempotent provisioning operation, poll safely, and reconcile unknown outcomes before retrying.'],
  ['qr','Your eSIM profile','activate','QR first, manual details nearby','Readable QR, copyable SM-DP+ address and activation code, ICCID and a second-device option.','Replace the non-installable fixture with authenticated profile details. EID is a device identifier, not an invented profile field.'],
  ['install','Install your eSIM','activate','Platform-specific install help','Keep the QR in view and explain the iPhone or Android route in short, readable steps.','Native installation links must use supported OS APIs and real provisioning data. Do not promise one-tap installation universally.'],
  ['settings','Set your mobile data','activate','Four settings that matter','Primary data, other-line data, switching and roaming are explicit checks, not a claim that the app changed settings.','Treat these as user confirmations. The browser cannot configure the device’s mobile-data settings.'],
  ['connected','Make it yours','activate','A coherent finish','Connection guidance ends with a profile label, folder and a clear route into the account.','Provisioned, installed and physically connected are different states. Use actual evidence before asserting connectivity in production.'],
  ['profile','Japan eSIM','manage','Everyday profile management','A legible usage card, plan details, quick actions and a useful route back to setup or support.','All usage, validity, network and allowance values need authoritative subscription data.'],
  ['label','Label & folder','manage','Quick profile organisation','Change a short label and folder without restarting activation; Cancel discards edits.','Persist changes to the authenticated owner. UI validation limits here are design choices, not established product rules.'],
  ['folders','Your folders','manage','A tidy travel workspace','Create folders, browse their contents and move a profile with a clear empty state.','Scope folders to the correct account and retain membership consistently across devices.'],
  ['topup','Add more data','manage','Top-up eligibility and selection','Compare fixed allowances, then review the actual cart before paying. Do not promise every profile supports top-up.','Quote supported products and confirm whether the existing profile can be used or a replacement is needed.'],
  ['usage','Usage & alerts','manage','Useful usage information','Consistent fixed-plan arithmetic and threshold controls, with functional chart labels instead of decorative telemetry.','Usage may be delayed. Notification toggles require permission and durable account settings.'],
  ['troubleshoot','Let’s get you online','support','A guided no-service checklist','Use the same installation recommendations as Start, with short actionable steps and a support handoff.','Do not infer the user’s settings or radio condition from checklist clicks.'],
  ['fair-use','About your speed','support','Fixed versus unlimited, honestly','Explain the fixed-allowance guarantee, local MNO rules for unlimited and a best-effort alternative route.','No universal speed, threshold, midnight reset or guaranteed improvement is promised.'],
  ['replacement','Another route','support','Consent before profile replacement','Keep the current eSIM until support advises otherwise and request review before any installation or validity changes.','Availability, cost and balance/validity carry-over require product confirmation. No silent profile replacement.'],
  ['support','Openline support','support','Knowledge, AI, then people','A short contextual conversation, suggested prompts and an explicit human-review path.','Connect real ticket/AI/human systems before claiming messages were delivered or an agent joined.'],
  ['orders','Orders & receipts','account','Order history beyond success','Paid and pending-refund entries with receipt access and a clear status timeline.','Use the real payment/refund ledger; do not invent refund deadlines or instantly resolved disputes.'],
  ['privacy','Privacy & account','account','Deliberate sensitive actions','Clear privacy preferences and separate export/deletion request confirmations with verification requirements.','Account export/deletion requires authenticated server workflows and retention-policy disclosure, not a local UI reset.'],
];
export const SCREENS=rows.map(([id,title,group,subtitle,description,backend],i)=>({id,title,group,subtitle,description,backend,number:i+1,code:'M'+String(i+1).padStart(2,'0')}));
export const DEFAULT={qty:1,email:'alex@example.com',giftIntent:false,payment:'card',unlocked:false,eligible:true,activated:false,role:'owner',label:'Japan adventure',folder:'Summer trip',folders:['Summer trip','Work','Archive'],topup:null,receiptPaid:true};
export const CODE='GAZE19-MULCH29-NYMPH13';
