import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,ArrowRight,ArrowUpRight,Check,CheckCircle2,ChevronRight,ChevronLeft,ChevronDown,Copy,CreditCard,Download,Folder,FolderPlus,Gift,Globe,Home,KeyRound,Lock,Mail,MessageCircle,MoreHorizontal,Plus,Minus,QrCode,Search,Settings,ShieldCheck,Signal,Smartphone,User,Wifi,X,AlertCircle,RefreshCw,LoaderCircle,Clock,Trash2,FileText,BatteryFull,Plane,Send,LifeBuoy,SlidersHorizontal,Bell,Receipt,ExternalLink,Pause,Play} from 'lucide-react';
import {SOURCE,FLOWS,SCREENS,DEFAULT,CODE} from './catalog.js';
import './style.css';

const iconMap={purchase:CreditCard,gift:Gift,activate:QrCode,manage:Folder,support:LifeBuoy,account:User};
const brand=import.meta.env.BASE_URL+'brand.png',qr=import.meta.env.BASE_URL+'esim-qr.png';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const initialScreen=()=>{const id=new URLSearchParams(location.hash.slice(1)).get('screen');return SCREENS.some(s=>s.id===id)?id:'cart';};
function Brand({compact=false}){return <span className="brand"><img src={brand} alt="" />{!compact&&<b>Openline</b>}</span>;}
function IconTile({icon:Icon=Smartphone,tone='orange',big=false}){return <span className={`icon-tile ${tone} ${big?'big':''}`}><Icon aria-hidden="true"/></span>;}
function Chip({children,tone='neutral'}){return <span className={`chip ${tone}`}>{children}</span>;}
function Button({children,onClick,kind='primary',icon:Icon=ArrowRight,disabled=false,type='button',...rest}){return <button type={type} className={`m-button ${kind}`} onClick={onClick} disabled={disabled} {...rest}><span>{children}</span>{Icon&&<Icon size={17} className="btn-arrow" aria-hidden="true"/>}</button>;}
function Row({icon:Icon=ChevronRight,title,detail,onClick,aside,destructive=false}){return <button className={`m-row ${destructive?'destructive':''}`} onClick={onClick}><span className="row-icon"><Icon size={19}/></span><span><b>{title}</b>{detail&&<small>{detail}</small>}</span>{aside||<ChevronRight size={17}/>}</button>;}
function Notice({children,tone='orange',icon:Icon=AlertCircle}){return <div className={`notice ${tone}`}><Icon size={17}/><p>{children}</p></div>;}
function Plan({session=DEFAULT,compact=false}){const data=session.topup?.data||10;return <div className={`plan-card ${compact?'compact':''}`}><span className="country-chip">JP</span><div><b>Japan · {data} GB</b><small>{session.topup?'Fixed-data top-up':'Fixed data · 30 days'}</small></div><Chip tone="orange">5G / LTE</Chip></div>;}
function Summary({session=DEFAULT}){const total=(session.topup?.price||12)*session.qty;return <div className="price-summary"><div><span>Subtotal</span><span>{money(total)}</span></div><div><span>Taxes in this quote</span><span>{money(0)}</span></div><div className="total"><b>Total</b><b>{money(total)}</b></div></div>;}
function Toggle({checked,onChange,label,detail}){return <label className="toggle-row"><span><b>{label}</b>{detail&&<small>{detail}</small>}</span><input type="checkbox" role="switch" checked={checked} onChange={e=>onChange(e.target.checked)}/><span className="switch" aria-hidden="true"/></label>;}
function StatusBar(){return <div className="status-bar"><b>9:41</b><span><Signal size={13}/><Wifi size={13}/><BatteryFull size={16}/></span></div>;}
function BottomNav({active='esims',go}){return <nav className="bottom-nav" aria-label="App navigation">{[['home',Home,'Home','profile'],['plans',Globe,'Plans','topup'],['esims',Smartphone,'eSIMs','folders'],['me',User,'Me','privacy']].map(([id,Icon,text,to])=><button key={id} className={active===id?'active':''} onClick={()=>go(to)}><Icon size={21}/><span>{text}</span></button>)}</nav>;}
function Sheet({data,onClose}){const ref=useRef(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} className="mobile-sheet" aria-labelledby="sheet-title" onCancel={onClose} onClick={e=>{if(e.target===ref.current){const r=ref.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}><div className="sheet-grip"/><button className="sheet-close" onClick={onClose} aria-label="Close dialog"><X/></button><IconTile icon={data.icon||ShieldCheck} big/><h2 id="sheet-title">{data.title}</h2><p>{data.text}</p>{data.content}{data.action&&<Button onClick={()=>{data.action();onClose();}} kind={data.destructive?'danger':'primary'}>{data.label||'Confirm'}</Button>}<Button kind="quiet" icon={null} onClick={onClose}>{data.cancel||'Not now'}</Button></dialog>;}

function Screen({id,session,setSession,go,back,scenario='default',preview=false}){
  const screen=SCREENS.find(s=>s.id===id);
  const pendingTimers=useRef([]);
  useEffect(()=>()=>pendingTimers.current.forEach(clearTimeout),[]);
  const later=(fn,ms)=>{const t=setTimeout(fn,ms);pendingTimers.current.push(t);};
  const [sheet,setSheet]=useState(null),[toast,setToast]=useState(''),[ready,setReady]=useState(false),[checked,setChecked]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(session.email),[code,setCode]=useState(CODE),[platform,setPlatform]=useState('ios'),[draft,setDraft]=useState(session.label),[folder,setFolder]=useState(session.folder),[newFolder,setNewFolder]=useState(''),[selectedFolder,setSelectedFolder]=useState('All'),[topup,setTopup]=useState(10),[message,setMessage]=useState(''),[messages,setMessages]=useState([]),[provision,setProvision]=useState(preview?'working':'working');
  const total=(session.topup?.price||12)*session.qty;
  const update=patch=>setSession({...session,...patch});
  function say(text){setToast(text);}
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{if(preview||id!=='provisioning')return;setProvision('working');const t=setTimeout(()=>{if(scenario==='failure')setProvision('failed');else{setProvision('ready');setSession(s=>({...s,activated:true}));}},matchMedia('(prefers-reduced-motion:reduce)').matches?100:2200);return()=>clearTimeout(t);},[id,scenario,preview]);
  const copy=async(text,label='Copied')=>{try{await navigator.clipboard.writeText(text);say(label);}catch{setSheet({title:'Copy these details',text:'Clipboard access is unavailable. Select and copy the text below.',content:<textarea readOnly value={text} aria-label="Text to copy"/>,cancel:'Close'});}};
  const confirmActivation=()=>setSheet({title:'Start this plan now?',text:'Your plan’s validity begins immediately. This purchase code will be consumed and can no longer be gifted. If you travel later, wait until you are ready.',icon:KeyRound,label:'Activate now',action:()=>{update({role:id==='gift-received'?'recipient':session.role});go('provisioning');}});
  const downloadReceipt=()=>{const txt=`Openline order OL-28417\nJapan · ${session.topup?.data||10} GB\nQuantity: ${session.qty}\nTotal: ${money(total)}\nReceipt email: ${session.email}\nDesign reference receipt. No payment was processed.\n`;const a=document.createElement('a'),u=URL.createObjectURL(new Blob([txt],{type:'text/plain'}));a.href=u;a.download='openline-order-OL-28417.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
  const field=(label,value,onChange,props={})=><label className="m-field"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} {...props}/></label>;
  const codeBlock=<div className="code-card"><span className="overline">Purchase code</span><code>{CODE}</code><button onClick={()=>copy(CODE,'Purchase code copied')} aria-label="Copy purchase code"><Copy size={18}/></button></div>;
  const qrBlock=<div className="qr-block"><img src={qr} alt="Example eSIM QR code for the design reference"/><span>Scan with your phone’s eSIM setup</span></div>;
  let content,footer,nav=['profile','folders','usage','orders','privacy'].includes(id);
  if(id==='cart'){
    content=<><p className="m-lead">A little preparation.<br/>A lot more freedom.</p>{session.qty>0?<><Plan session={session}/><div className="quantity"><span>Quantity</span><div><button aria-label="Decrease quantity" onClick={()=>update({qty:Math.max(1,session.qty-1)})} disabled={session.qty===1}><Minus size={16}/></button><b>{session.qty}</b><button aria-label="Increase quantity" onClick={()=>update({qty:Math.min(3,session.qty+1)})} disabled={session.qty===3}><Plus size={16}/></button></div><button className="text-link" onClick={()=>update({qty:0})}>Remove</button></div><Summary session={session}/><Notice icon={KeyRound}>You’ll receive a purchase code. Your plan starts only when you activate it.</Notice><div className="trust-row"><ShieldCheck size={16}/> Secure payment <span>·</span> Keep or gift later</div></>:<div className="center-state"><IconTile icon={Globe} big/><h3>Your cart is empty</h3><p>Your next connection is one plan away.</p><Button onClick={()=>update({qty:1})}>Restore Japan plan</Button></div>}</>;
    footer=session.qty>0?<Button onClick={()=>go('delivery')}>Continue · {money(total)}</Button>:null;
  }else if(id==='delivery'){
    content=<><Plan session={session} compact/><h3>Where should we send it?</h3><p className="m-lead">Your receipt and purchase code, in one place.</p>{field('Receipt email',email,setEmail,{type:'email',autoComplete:'email',placeholder:'you@example.com'})}{error&&<p className="field-error" role="alert">{error}</p>}<div className="m-section-title">Who is this purchase for?</div><div className="segmented">{['Myself','Someone else'].map((v,i)=><button className={session.giftIntent===!!i?'selected':''} key={v} onClick={()=>update({giftIntent:!!i})}>{v}</button>)}</div><Notice icon={Gift}>{session.giftIntent?'You stay the purchase owner. After payment, unlock the unused code before sharing it.':'You can still decide to gift an unused purchase code later.'}</Notice><p className="muted-note">This email receives purchase validation, even if you gift the code.</p></>;
    footer=<Button onClick={()=>{if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setError('Enter a valid receipt email.');return;}update({email});go('payment');}}>Continue to payment</Button>;
  }else if(id==='payment'){
    content=<><div className="total-banner"><small>Amount to pay</small><strong>{money(total)}</strong><span>Japan · {session.topup?.data||10} GB</span></div><h3>Choose how to pay</h3>{[['card','Visa ending 4242','Saved payment method',CreditCard],['wallet','Apple Pay','Confirm on your device',Smartphone],['paypal','PayPal','Continue in a secure payment window',ExternalLink]].map(([value,title,detail,Icon])=><label className={`payment-choice ${session.payment===value?'selected':''}`} key={value}><Icon size={23}/><span><b>{title}</b><small>{detail}</small></span><input type="radio" name={'pay-'+id} checked={session.payment===value} onChange={()=>update({payment:value})}/></label>)}<Notice icon={Lock}>Payment details stay with the payment provider. We don’t ask for your banking password.</Notice></>;
    footer=<Button icon={Lock} onClick={()=>go(session.payment==='card'?'bank':'pending')}>Pay {money(total)}</Button>;
  }else if(id==='bank'){
    content=<div className="center-state"><IconTile icon={ShieldCheck} big/><Chip>Payment authentication</Chip><h2>Approve with<br/>your bank.</h2><p>Complete the secure authentication step, then return here.</p><div className="bank-order"><span>Openline · Japan eSIM</span><strong>{money(total)}</strong><small>Visa •••• 4242</small></div><div className="loading-line"/><Notice tone="neutral" icon={Lock}>Never share your bank password or verification code in chat.</Notice></div>;
    footer=<><Button onClick={()=>go('pending')}>I’ve completed approval</Button><Button kind="quiet" icon={null} onClick={()=>go('payment')}>Choose another payment method</Button></>;
  }else if(id==='pending'){
    content=<div className="center-state"><IconTile icon={scenario==='failure'?AlertCircle:RefreshCw} big/><Chip tone={scenario==='failure'?'red':'orange'}>{scenario==='failure'?'Payment needs attention':'Checking with the provider'}</Chip><h2>{scenario==='failure'?'Let’s try another route.':'One moment.\nWe’re checking.'}</h2><p>{scenario==='failure'?'The provider reports this payment as unsuccessful. Choose another method to continue.':'Your payment result is not confirmed yet. Don’t pay again while we check this attempt.'}</p><Plan session={session}/><div className="mini-timeline"><span className="done">Payment started</span><span className={scenario==='failure'?'':'current'}>Provider confirmation</span><span>Purchase code ready</span></div>{error&&<Notice>{error}</Notice>}</div>;
    footer=<Button icon={scenario==='failure'?CreditCard:RefreshCw} disabled={busy} onClick={()=>{if(scenario==='failure'){go('payment');return;}setBusy(true);later(()=>{setBusy(false);if(scenario==='pending')setError('Still awaiting confirmation. You can safely check this same payment again.');else{update({receiptPaid:true});go('receipt');}},450);}}>{busy?'Checking…':scenario==='failure'?'Change payment method':'Check payment status'}</Button>;
  }else if(id==='receipt'){
    content=<><div className="receipt-heading"><IconTile icon={Receipt}/><div><Chip tone="green">Paid</Chip><h2>Your order receipt</h2><small>Order OL-28417</small></div></div><Plan session={session}/><Summary session={session}/><div className="detail-lines"><div><span>Payment</span><b>{session.payment==='card'?'Visa •••• 4242':session.payment==='wallet'?'Apple Pay':'PayPal'}</b></div><div><span>Receipt</span><b>{session.email}</b></div></div><Row icon={KeyRound} title="Your purchase code" detail="Keep it, activate it or unlock it as a gift" onClick={()=>go('code')}/><Button kind="secondary" icon={Download} onClick={downloadReceipt}>Download receipt</Button></>;
    footer=<Button onClick={()=>go('code')}>View purchase code</Button>;
  }else if(id==='code'){
    content=<><Plan session={session}/><div className="chips"><Chip tone={session.activated?'green':'orange'}>{session.activated?'Activated':'Not activated'}</Chip><Chip><ShieldCheck size={12}/> Purchase validated</Chip></div>{codeBlock}<p className="m-lead">A purchase code becomes an eSIM profile only when you activate it.</p><div className="choice-stack"><Row icon={KeyRound} title={session.activated?'View your eSIM':'Activate this plan'} detail={session.activated?'Your QR code and installation details':'Start only when you’re ready to travel'} onClick={()=>go(session.activated?'qr':'readiness')}/>{!session.activated&&<Row icon={Gift} title="Gift this purchase" detail="Unlock the unused code before sharing" onClick={()=>go('unlock')}/>}<Row icon={Folder} title="Keep it for later" detail="Find it in your orders whenever you need it" onClick={()=>go('orders')}/></div><p className="muted-note">Purchase code ≠ eSIM activation code. Your phone’s setup details come after activation.</p></>;
  }else if(id==='unlock'){
    content=<><div className="center-state compact-center"><IconTile icon={Gift} big/><h2>A connection.<br/>A thoughtful gift.</h2><p>Transfer an unused purchase without starting the plan.</p></div><Plan session={session}/><div className="simple-steps"><p><b>1</b> Unlock your purchase code.</p><p><b>2</b> Share it privately with your recipient.</p><p><b>3</b> They activate when they are ready.</p></div><Notice icon={Mail}>You still receive an email to validate the purchase. Unlocking does not bypass that step.</Notice>{session.activated&&<Notice tone="red">This code has already been activated and can’t be gifted.</Notice>}</>;
    footer=<Button icon={Lock} disabled={session.activated} onClick={()=>setSheet({title:'Unlock for transfer?',text:'Anyone with the unlocked code can redeem it. Share it privately. Unlocking does not start the plan or remove the owner’s email-validation step.',icon:Gift,label:'Unlock purchase code',action:()=>{update({unlocked:true});go('gift-ready');}})}>Unlock for gifting</Button>;
  }else if(id==='gift-ready'){
    content=<><div className="center-state compact-center"><IconTile icon={Gift} big/><Chip tone="green">Unlocked · not activated</Chip><h2>Ready to make<br/>someone’s trip.</h2></div>{codeBlock}<div className="gift-message"><span className="overline">Your gift message</span><p>A little gift for your next trip: Japan, 10 GB. Redeem your Openline purchase code when you’re ready to start the plan.</p><small>Owner purchase validation still applies.</small></div><Notice icon={Lock}>Share only with your recipient. Anyone holding the unlocked code can use it.</Notice></>;
    footer=<><Button icon={Copy} onClick={()=>copy(`A gift for your trip: Openline Japan 10 GB. Purchase code: ${CODE}. Redeem at https://openline.com/start when ready to start the plan. Owner purchase validation still applies.`,'Gift message copied')}>Copy gift message</Button><Button kind="quiet" icon={null} onClick={()=>go('orders')}>Back to my account</Button></>;
  }else if(id==='gift-received'){
    content=<><div className="center-state compact-center"><IconTile icon={Gift} big/><h2>Someone’s got<br/>your trip covered.</h2><p>Check your purchase code. Nothing starts yet.</p></div>{field('Gift purchase code',code,setCode,{spellCheck:false,autoCapitalize:'characters'})}<Plan session={session}/><Chip tone={scenario==='locked'?'neutral':'green'}>{scenario==='locked'?'Transfer locked':'Unlocked gift'}</Chip>{scenario==='locked'?<Notice>Ask the sender to unlock this purchase code before you redeem it.</Notice>:<Notice icon={Clock}>Keep it for later, or activate when you are ready. Activation starts validity immediately.</Notice>}{error&&<p className="field-error" role="alert">{error}</p>}</>;
    footer=<><Button disabled={scenario==='locked'} onClick={()=>{if(code.trim().toUpperCase()!==CODE){setError('We couldn’t verify this code. Check all three parts and try again.');return;}update({role:'recipient',unlocked:true});go(scenario==='pending'?'gift-pending':'readiness');}}>Review & redeem</Button><Button kind="quiet" icon={null} onClick={()=>go('orders')}>Keep it for later</Button></>;
  }else if(id==='gift-pending'){
    content=<div className="center-state"><IconTile icon={Mail} big/><Chip tone="orange">Purchase validation pending</Chip><h2>One quick step<br/>for the sender.</h2><p>The purchase owner needs to finish email validation before this gift can be activated.</p><Plan session={session}/><Notice icon={ShieldCheck}>Your gift has not been activated. Checking again won’t start its validity.</Notice><button className="text-link" onClick={()=>copy('Could you finish the Openline purchase-validation email for the code you gifted me? I can redeem it once validation is complete.','Sender-help message copied')}>Copy a message for the sender <Copy size={14}/></button></div>;
    footer=<Button icon={RefreshCw} onClick={()=>{update({eligible:true,role:'recipient',unlocked:true});go('gift-received');}}>Check again</Button>;
  }else if(id==='readiness'){
    content=<><Plan session={session}/><div className="center-state compact-center"><IconTile icon={KeyRound} big/><h2>A quick check<br/>before we start.</h2><p>Your plan begins now, not on a future travel date.</p></div><Toggle checked={ready} onChange={setReady} label="I’m ready to start this plan now" detail="Activate just before or at your destination."/><Notice icon={Wifi}>Use a trusted private Wi-Fi connection. Public airport Wi-Fi or cellular setup may block activation.</Notice><p className="muted-note">Once activated, this purchase code can no longer be gifted.</p></>;
    footer=<Button disabled={!ready} onClick={confirmActivation}>Activate my plan</Button>;
  }else if(id==='provisioning'){
    content=<div className="center-state"><IconTile icon={provision==='failed'?AlertCircle:provision==='ready'?CheckCircle2:RefreshCw} big/><Chip tone={provision==='ready'?'green':provision==='failed'?'red':'orange'}>{provision==='ready'?'Profile created':provision==='failed'?'Setup needs attention':'Creating profile'}</Chip><h2>{provision==='ready'?'Your eSIM\nis ready.':provision==='failed'?'Let’s finish\nthis safely.':'Turning your code\ninto a connection.'}</h2><p>{provision==='failed'?'We couldn’t confirm provisioning. Check this request before starting again.':'Keep this page open while we prepare your profile and installation details.'}</p><div className="provision-orbit"><Smartphone size={42}/>{provision==='working'?<LoaderCircle className="spin" size={76}/>:<Check size={22}/>}</div><div className="mini-timeline"><span className="done">Purchase code checked</span><span className={provision==='ready'?'done':'current'}>eSIM profile prepared</span><span className={provision==='ready'?'done':''}>QR and manual details</span></div></div>;
    footer=<Button disabled={provision==='working'} icon={provision==='failed'?RefreshCw:ArrowRight} onClick={()=>{if(provision==='failed'){setProvision('working');later(()=>{setProvision('ready');update({activated:true});},700);}else go('qr');}}>{provision==='working'?'Preparing your profile…':provision==='failed'?'Check provisioning request':'View my eSIM'}</Button>;
  }else if(id==='qr'){
    content=<><Plan session={session} compact/><Chip tone="green">Activated · ready to install</Chip>{qrBlock}<details className="manual-details"><summary>Manual installation details <ChevronDown size={16}/></summary>{[['SM-DP+ address','consumer.openline.invalid'],['Activation code','QA-NOT-INSTALLABLE-2026'],['ICCID','8944 0000 0000 0000 001']].map(([k,v])=><button key={k} className="manual-row" onClick={()=>copy(v,k+' copied')}><span><small>{k}</small><code>{v}</code></span><Copy size={15}/></button>)}</details><button className="text-link centered" onClick={()=>setSheet({title:'Installing on another device?',text:'Display this QR on one screen, then use the other phone’s Add eSIM flow to scan it. Keep your profile details private.',icon:QrCode,cancel:'Understood'})}>Using another device?</button></>;
    footer=<Button onClick={()=>go('install')}>Install & connect</Button>;
  }else if(id==='install'){
    content=<><div className="small-qr"><img src={qr} alt="Example eSIM QR"/><div><b>{session.label}</b><small>Your installation code</small><button className="text-link" onClick={()=>go('qr')}>View full QR</button></div></div><div className="segmented"><button className={platform==='ios'?'selected':''} onClick={()=>setPlatform('ios')}>iPhone</button><button className={platform==='android'?'selected':''} onClick={()=>setPlatform('android')}>Android</button></div><div className="install-steps">{(platform==='ios'?[['Open Settings','Mobile Service / Cellular → Add eSIM.'],['Use QR code','Scan your eSIM QR, or enter manual details.'],['Add the mobile plan','Follow the phone’s prompts and label it Openline.']]:[['Open Settings','Connections / Network & internet → SIMs.'],['Add an eSIM','Choose Download a SIM or Add eSIM.'],['Scan and follow the prompts','Menus vary by phone manufacturer.']]).map(([a,b],i)=><div key={a}><b>{i+1}</b><span><strong>{a}</strong><small>{b}</small></span></div>)}</div><Notice icon={Wifi}>Stay on private Wi-Fi until installation finishes.</Notice></>;
    footer=<Button onClick={()=>go('settings')}>Installed? Set up mobile data</Button>;
  }else if(id==='settings'||id==='troubleshoot'){
    const help=id==='troubleshoot',checks=[['primary','Openline is my primary data line'],['other','Mobile data on other SIMs is OFF'],['switching','Automatic data switching is OFF'],['roaming','Openline data roaming is ON']];
    content=<><p className="m-lead">{help?'Let’s check the essentials before changing your profile.':'Four settings. One clear connection.'}</p><Plan session={session} compact/>{checks.map(([key,text])=><label className="setting-check" key={key}><input type="checkbox" checked={!!checked[key]} onChange={e=>setChecked({...checked,[key]:e.target.checked})}/><span>{text}</span></label>)}<div className="airplane-tip"><IconTile icon={Plane}/><div><b>Give the connection a refresh</b><p>Airplane mode ON, then OFF. Wait for the network and try a webpage.</p></div></div><p className="muted-note">These checks don’t change phone settings for you. Keep calls/texts on your other line if you need them.</p></>;
    footer=help?<><Button onClick={()=>go('support')}>I still need help</Button><Button kind="quiet" icon={null} onClick={()=>go('fair-use')}>Connected, but slower than expected?</Button></>:<Button disabled={Object.values(checked).filter(Boolean).length<4} onClick={()=>go('connected')}>Continue to my eSIM</Button>;
  }else if(id==='connected'){
    content=<><div className="center-state compact-center"><IconTile icon={CheckCircle2} big/><Chip tone="green">Your setup is complete</Chip><h2>Make this<br/>connection yours.</h2><p>Try a webpage to confirm you’re online, then give this profile a familiar name.</p></div>{field('eSIM label',draft,setDraft,{maxLength:32})}<label className="m-field"><span>Folder</span><select aria-label="Folder" value={folder} onChange={e=>setFolder(e.target.value)}>{session.folders.map(f=><option key={f}>{f}</option>)}</select></label></>;
    footer=<Button onClick={()=>{if(!draft.trim()){setError('Add a label for this eSIM.');return;}update({label:draft.trim(),folder,activated:true});go('profile');}}>Save & go to my eSIMs</Button>;
  }else if(id==='profile'){
    content=<><div className="profile-subtitle"><span className="country-chip">JP</span><div><b>{session.label}</b><small>{session.folder} · Fixed data</small></div><button aria-label="Edit eSIM" onClick={()=>go('label')}><SlidersHorizontal size={19}/></button></div><div className="usage-card"><div><span>Japan · 5G / LTE</span><Chip>Active</Chip></div><strong>6.8<span> GB left</span></strong><div className="usage-track"><i/></div><p>6.8 of 10 GB remaining <span>68%</span></p></div><div className="quick-actions"><button onClick={()=>go('qr')}><QrCode/><span>eSIM details</span></button><button onClick={()=>go('topup')}><Plus/><span>Add data</span></button><button onClick={()=>go('usage')}><Signal/><span>Usage</span></button></div><div className="detail-lines"><div><span>Plan</span><b>10 GB · 30 days</b></div><div><span>Profile status</span><b>Active</b></div><div><span>Folder</span><b>{session.folder}</b></div></div><Row icon={LifeBuoy} title="Connection help" detail="Settings, speed and support" onClick={()=>go('troubleshoot')}/></>;
  }else if(id==='label'){
    content=<><Plan session={session} compact/>{field('eSIM label',draft,setDraft,{maxLength:32,placeholder:'e.g. Japan adventure'})}<label className="m-field"><span>Folder</span><select aria-label="Folder" value={folder} onChange={e=>setFolder(e.target.value)}>{session.folders.map(f=><option key={f}>{f}</option>)}</select></label><Notice icon={Folder}>Labels and folders help you organise. They don’t change your plan, number or activation details.</Notice>{error&&<p className="field-error" role="alert">{error}</p>}</>;
    footer=<><Button onClick={()=>{if(!draft.trim()){setError('Enter a label before saving.');return;}update({label:draft.trim(),folder});go('profile');}}>Save changes</Button><Button kind="quiet" icon={null} onClick={()=>go('profile')}>Cancel</Button></>;
  }else if(id==='folders'){
    content=<><div className="folder-top"><p className="m-lead">A place for every trip.</p><button aria-label="Create folder" onClick={()=>setSheet({title:'Create a folder',text:'Choose a short name for this group of eSIMs.',icon:FolderPlus,content:<FolderForm onCreate={name=>{setSession(s=>({...s,folders:[...new Set([...s.folders,name])]}));setSelectedFolder(name);setSheet(null);}}/>,cancel:'Cancel'})}><FolderPlus size={22}/></button></div><div className="folder-list">{['All',...session.folders].map(f=><button key={f} className={selectedFolder===f?'selected':''} onClick={()=>setSelectedFolder(f)}><Folder size={18}/><span>{f}</span><small>{f==='All'||f===session.folder?1:0}</small></button>)}</div><div className="m-section-title">{selectedFolder==='All'?'All eSIMs':selectedFolder}</div>{selectedFolder==='All'||selectedFolder===session.folder?<div className="folder-profile"><Plan session={session}/><b>{session.label}</b><div className="actions"><Button kind="secondary" onClick={()=>go('profile')}>View profile</Button><button className="text-link" onClick={()=>go('label')}>Move / rename</button></div></div>:<div className="empty-folder"><Folder size={30}/><h3>Ready for your next trip</h3><p>Move an eSIM here from its label and folder settings.</p><button className="text-link" onClick={()=>go('label')}>Move an eSIM here</button></div>}</>;
  }else if(id==='topup'){
    content=<><Plan session={session} compact/><p className="m-lead">A little more data.<br/>No guesswork.</p><div className="topup-grid">{[[3,8],[5,10],[10,12]].map(([data,price])=><button className={topup===data?'selected':''} key={data} onClick={()=>setTopup(data)}><span>{data===10?'Best value':'Fixed data'}</span><strong>{data} GB</strong><b>{money(price)}</b></button>)}</div><Notice icon={ShieldCheck}>Every purchased GB at full available network speed, without usage-based throttling.</Notice><p className="muted-note">Top-up availability depends on your plan. We’ll confirm whether it uses this profile or needs a new one before activation.</p></>;
    footer=<Button onClick={()=>{update({topup:{data:topup,price:topup===3?8:topup===5?10:12},qty:1});go('cart');}}>Review top-up · {money(topup===3?8:topup===5?10:12)}</Button>;
  }else if(id==='usage'){
    content=<><div className="usage-ring" role="img" aria-label="32 percent used, 6.8 gigabytes remaining of 10"><div><strong>6.8 <small>GB</small></strong><span>remaining</span></div></div><div className="usage-totals"><span><b>3.2 GB</b> used</span><span><b>10 GB</b> total</span></div><h3>This week</h3><div className="usage-bars">{[35,52,30,76,45,88,50].map((v,i)=><div key={i}><span style={{height:v+'%'}}/><small>{['M','T','W','T','F','S','S'][i]}</small></div>)}</div><p className="muted-note">Usage may update with a delay.</p><h3>Data reminders</h3>{[50,80,100].map(n=><Toggle key={n} checked={checked[n]!==false} onChange={v=>setChecked({...checked,[n]:v})} label={`At ${n}% used`}/> )}</>;
  }else if(id==='fair-use'){
    content=<><div className="policy-card"><IconTile icon={ShieldCheck}/><h3>Fixed data, fully yours.</h3><p>Buy 10 GB and get all 10 GB at full available network speed, with no usage-based throttling.</p><Chip>Recommended for predictable usage</Chip></div><div className="policy-card"><IconTile icon={Signal} tone="neutral"/><h3>Unlimited, with local rules.</h3><p>Openline adds no data cap or throttling. A local mobile network may temporarily reduce speed after heavy use within 24 hours.</p></div><Notice>Thresholds and recovery vary. If it happens too often, we’ll try another profile or provider with a better-fitting fair-use policy. Improvement isn’t guaranteed.</Notice></>;
    footer=<Button onClick={()=>go('replacement')}>Explore another route</Button>;
  }else if(id==='replacement'){
    content=<><div className="route-change"><IconTile icon={Smartphone} tone="neutral"/><ArrowRight/><IconTile icon={Smartphone}/></div><h2>A different profile.<br/>A fresh route.</h2><p className="m-lead">When changing networks is not enough, support can review another provider setup.</p><div className="simple-steps"><p><Check size={16}/> A new profile may need installation.</p><p><Check size={16}/> Local rules still apply.</p><p><Check size={16}/> A better result is not guaranteed.</p></div><Notice icon={ShieldCheck}>Keep your current eSIM until support tells you otherwise. We’ll confirm availability, charges and what happens to remaining data and validity first.</Notice><label className="setting-check"><input type="checkbox" checked={ready} onChange={e=>setReady(e.target.checked)}/><span>I understand a new profile may need setup.</span></label></>;
    footer=<Button disabled={!ready} onClick={()=>setSheet({title:'Ask support to review?',text:'This prepares a support conversation. It does not replace your eSIM or change its validity. Keep your existing profile installed.',label:'Continue to support',icon:LifeBuoy,action:()=>go('support')})}>Request a profile review</Button>;
  }else if(id==='support'){
    content=<><div className="support-path"><span>Knowledge base</span><ChevronRight size={12}/><span>Openline AI</span><ChevronRight size={12}/><span>People</span></div><div className="support-brand"><Brand compact/><div><b>Here to help you stay connected</b><small>Japan eSIM · connection support</small></div></div><div className="chat-bubble">Hi! What’s happening with your connection? We can start with the setup checks, explain local fair use, or prepare a profile review.</div><div className="chat-prompts">{['No service','Speed feels slow','Review my profile'].map(t=><button key={t} onClick={()=>setMessages([...messages,{text:t,by:'user'},{text:t==='No service'?'Let’s check your mobile-data and roaming settings first.':t==='Speed feels slow'?'We can explain your plan’s local network rules and look at the next step.':'A specialist needs to confirm availability, installation and any effect on remaining data before a profile change.',by:'bot'}])}>{t}</button>)}</div>{messages.map((m,i)=><div key={i} className={'chat-bubble '+(m.by==='user'?'user':'')}>{m.text}</div>)}<button className="text-link" onClick={()=>setSheet({title:'Continue with a person',text:'A human specialist can review this issue with your plan context. In the live app, availability and ticket status must come from the support system.',icon:User,cancel:'Back to conversation'})}>Ask for a human specialist</button></>;
    footer=<form className="chat-compose" onSubmit={e=>{e.preventDefault();if(!message.trim())return;setMessages([...messages,{by:'user',text:message.trim()},{by:'bot',text:'Thanks for explaining. Start with the setup checklist, or request a specialist review if the issue continues.'}]);setMessage('');}}><input value={message} maxLength={500} onChange={e=>setMessage(e.target.value)} aria-label="Message" placeholder="How can we help?"/><button aria-label="Send message" disabled={!message.trim()}><Send size={19}/></button></form>;
  }else if(id==='orders'){
    content=<><p className="m-lead">Your purchases.<br/>Always easy to find.</p><button className="order-card" onClick={()=>go('receipt')}><div><span className="country-chip">JP</span><Chip tone="green">Paid</Chip></div><h3>Japan · 10 GB</h3><p>Order OL-28417 <b>{money(total)}</b></p><span>Receipt & purchase code <ChevronRight size={15}/></span></button><button className="order-card" onClick={()=>setSheet({title:'Refund being reviewed',text:'Order OL-27906 is awaiting a support decision. We’ll show the actual refund status and next step here. Processing time depends on the payment provider.',icon:Clock,cancel:'Close'})}><div><span className="country-chip neutral">MX</span><Chip>Refund review</Chip></div><h3>Mexico · 5 GB</h3><p>Order OL-27906 <b>$12.00</b></p><span>View status <ChevronRight size={15}/></span></button><Notice icon={Gift}>Received a gift? Review the unlocked purchase code without starting it.</Notice><Button kind="secondary" icon={Gift} onClick={()=>go('gift-received')}>I received a gift</Button></>;
  }else if(id==='privacy'){
    content=<><div className="account-card"><span>A</span><div><b>Alex Rivera</b><small>alex@example.com</small></div></div><h3>Your preferences</h3><Toggle checked={!!checked.marketing} onChange={v=>setChecked({...checked,marketing:v})} label="Marketing emails" detail="Offers and travel news. Off by default."/><Toggle checked={checked.alerts!==false} onChange={v=>setChecked({...checked,alerts:v})} label="Plan and usage alerts" detail="Useful updates about your eSIM."/><h3>Your information</h3><Row icon={Download} title="Request my account data" detail="Identity verification is required" onClick={()=>setSheet({title:'Request a data export',text:'For your privacy, the live app must verify your identity before preparing an account export. This includes your account information and purchase history.',icon:Download,cancel:'Understood'})}/><Row icon={Trash2} title="Request account deletion" detail="Review consequences before confirming" destructive onClick={()=>setSheet({title:'Before you delete your account',text:'Review active plans and download any receipts you need. Identity verification and applicable record-retention rules must be explained before a deletion request is submitted.',icon:ShieldCheck,cancel:'Keep my account',label:'Review verification requirements',destructive:true,action:()=>say('Identity verification is required before a deletion request can be submitted.')})}/><Notice icon={Lock}>Account deletion, data export and saved preferences require your authenticated account.</Notice></>;
  }
  return <div className="app-screen"><StatusBar/><header className="app-header"><button onClick={back} aria-label="Back"><ArrowLeft size={21}/></button><h2>{screen.title}</h2><button aria-label="Help with this screen" onClick={()=>setSheet({title:screen.subtitle,text:screen.description,icon:LifeBuoy,cancel:'Got it'})}><LifeBuoy size={20}/></button></header><main className="screen-scroll"><div className="screen-content">{content}{error&&id==='connected'&&<p className="field-error" role="alert">{error}</p>}</div></main>{footer&&<footer className="screen-footer">{footer}</footer>}{nav&&<BottomNav active={['orders','privacy'].includes(id)?'me':'esims'} go={go}/>}<div className="home-indicator"/>{toast&&<div className="phone-toast" role="status">{toast}</div>}{sheet&&!preview&&<Sheet data={sheet} onClose={()=>setSheet(null)}/>}</div>;
}
function FolderForm({onCreate}){const [name,setName]=useState('');return <form onSubmit={e=>{e.preventDefault();if(name.trim())onCreate(name.trim());}}><label className="m-field"><span>Folder name</span><input value={name} maxLength={28} onChange={e=>setName(e.target.value)} autoFocus placeholder="e.g. Autumn in Asia"/></label><Button type="submit" disabled={!name.trim()} icon={FolderPlus}>Create folder</Button></form>;}

function App(){
  const [view,setView]=useState(initialScreen),[mode,setMode]=useState(location.hash.includes('screen=')||matchMedia('(max-width:700px)').matches?'player':'gallery'),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[flow,setFlow]=useState(()=>SCREENS.find(s=>s.id===initialScreen()).group),[session,setSession]=useState({...DEFAULT}),[scenario,setScenario]=useState('default'),[history,setHistory]=useState([]),[notice,setNotice]=useState('');
  const selected=SCREENS.find(s=>s.id===view),journey=FLOWS.find(f=>f.id===flow),index=journey.steps.indexOf(view);
  const go=id=>{setHistory(h=>[...h,view]);setView(id);if(!journey.steps.includes(id))setFlow(SCREENS.find(s=>s.id===id).group);setScenario('default');setMode('player');historyReplace(id);};
  const historyReplace=id=>window.history.replaceState(null,'','#screen='+id);
  const back=()=>{const last=history.at(-1);if(last){setHistory(h=>h.slice(0,-1));setView(last);if(!journey.steps.includes(last))setFlow(SCREENS.find(s=>s.id===last).group);setScenario('default');historyReplace(last);}else if(index>0)go(journey.steps[index-1]);else setMode('gallery');};
  const startFlow=id=>{const f=FLOWS.find(f=>f.id===id);setFlow(id);setSession({...DEFAULT});setHistory([]);setScenario('default');setView(f.steps[0]);setMode('player');historyReplace(f.steps[0]);document.getElementById('workspace')?.scrollIntoView({behavior:'smooth'});};
  useEffect(()=>{const changed=()=>{const id=initialScreen();setView(id);setMode(location.hash.includes('screen=')?'player':'gallery');};addEventListener('hashchange',changed);return()=>removeEventListener('hashchange',changed);},[]);
  useEffect(()=>{const fn=e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]'))setMode('gallery');};addEventListener('keydown',fn);return()=>removeEventListener('keydown',fn);},[]);
  const filtered=SCREENS.filter(s=>(filter==='all'||s.group===filter)&&`${s.title} ${s.subtitle} ${s.description}`.toLowerCase().includes(query.toLowerCase()));
  const copyLink=async()=>{try{await navigator.clipboard.writeText('https://openline-anims-review.vercel.app/mobile#screen='+view);setNotice('View link copied.');}catch{setNotice('Copy this view URL from your browser’s address bar.');}setTimeout(()=>setNotice(''),3500);};
  return <><header className="lab-header"><a href="/delivery"><Brand/></a><span className="lab-badge">Mobile / Extra views</span><nav><a href={SOURCE} target="_blank" rel="noopener">Irina’s originals <ArrowUpRight size={14}/></a><a href="/delivery">Delivery <ArrowUpRight size={14}/></a><a href="/qa">QA <ArrowUpRight size={14}/></a></nav></header><main className="lab-main"><section className="lab-hero"><div><p className="eyebrow">Extending the app, not reinventing it</p><h1>The next parts<br/>of the <span>Openline experience.</span></h1><p className="lab-lead">28 additional views. Six connected journeys. Built from the same mobile design language as Irina’s screens, with the details between “buy” and “connected” properly thought through.</p><div className="lab-actions"><button className="lab-button primary" onClick={()=>startFlow('purchase')}>Walk a workflow <ArrowRight size={17}/></button><a className="lab-button" href="/mobile/implementation.md" target="_blank" rel="noopener">Implementation notes <FileText size={17}/></a></div></div><aside className="lineage"><Brand/><h2>Same foundation.<br/>More of the journey.</h2><div className="lineage-chips"><span>React 18</span><span>Tailwind</span><span>Lucide</span></div><p>Openline orange · native UI font · 24px phone corners · familiar cards, tabs and bottom navigation.</p><div className="swatch-row"><i/><i/><i/><i/></div><small>Reference: Irina’s 19-screen app delivery. These are additional design proposals, not changes to her original page.</small></aside></section>
  <section className="workflow-strip" aria-label="Workflows">{FLOWS.map(f=>{const Icon=iconMap[f.id];return <button key={f.id} className={mode==='player'&&flow===f.id?'active':''} onClick={()=>startFlow(f.id)}><Icon size={21}/><span>{f.short}</span><small>{f.steps.length} linked views</small></button>;})}</section>
  <section id="workspace"><div className="workspace-toolbar"><div className="view-toggle"><button className={mode==='gallery'?'selected':''} onClick={()=>{setMode('gallery');window.history.replaceState(null,'',location.pathname);}}>All 28 views</button><button className={mode==='player'?'selected':''} onClick={()=>{setMode('player');historyReplace(view);}}>Interactive flow</button></div>{mode==='gallery'?<div className="gallery-tools"><label><Search size={16}/><input placeholder="Find a screen…" aria-label="Find a screen" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter by workflow" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Every workflow</option>{FLOWS.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div>:<div className="player-tools"><select aria-label="Jump to a screen" value={view} onChange={e=>{const next=SCREENS.find(s=>s.id===e.target.value);setFlow(next.group);go(next.id);}}>{SCREENS.map(s=><option value={s.id} key={s.id}>{s.code} · {s.title}</option>)}</select><button className="lab-button compact" onClick={copyLink}><Copy size={15}/> Copy view link</button></div>}</div>
  <p className="review-boundary"><ShieldCheck size={14}/> Interactive design reference. No real payments, emails, profile activations, device changes or account deletion are performed.</p>
  {mode==='gallery'?<><div className="gallery-count">{filtered.length} views · select any screen to explore it</div><div className="phone-gallery">{filtered.map(s=><article className="gallery-card" key={s.id}><div className="gallery-card-head"><span>{s.code}</span><small>{FLOWS.find(f=>f.id===s.group).short}</small></div><div className="phone-frame thumbnail" aria-hidden="true"><div inert=""><Screen key={s.id} id={s.id} session={{...DEFAULT,unlocked:s.id==='gift-ready',activated:['qr','profile'].includes(s.id)}} setSession={()=>{}} go={()=>{}} back={()=>{}} preview/></div></div><div className="gallery-caption"><h2>{s.title}</h2><p>{s.subtitle}</p><button onClick={()=>{setFlow(s.group);setSession({...DEFAULT});go(s.id);document.getElementById('workspace').scrollIntoView({behavior:'smooth'});}}>Open view <ArrowUpRight size={15}/></button></div></article>)}</div>{!filtered.length&&<div className="no-results"><Search size={32}/><h2>No matching screen.</h2><p>Try a different workflow or search phrase.</p><button className="lab-button" onClick={()=>{setQuery('');setFilter('all');}}>Show all views</button></div>}</>:
  <div className="player-layout"><aside className="journey-panel"><p className="eyebrow">Connected workflow</p><h2>{journey.name}</h2><p>{journey.description}</p><ol>{journey.steps.map((id,i)=>{const s=SCREENS.find(s=>s.id===id);return <li key={id}><button className={view===id?'current':''} onClick={()=>go(id)}><span>{String(i+1).padStart(2,'0')}</span><b>{s.title}</b>{view===id&&<ChevronRight size={15}/>}</button></li>;})}</ol><button className="text-link" onClick={()=>startFlow(flow)}><RefreshCw size={14}/> Restart this workflow</button></aside><div className="player-phone-stage"><div className="phone-frame player-phone"><Screen key={view+'-'+scenario} id={view} session={session} setSession={setSession} go={go} back={back} scenario={scenario}/></div><div className="screen-pager"><button aria-label="Previous view" disabled={index<=0} onClick={()=>go(journey.steps[index-1])}><ChevronLeft size={18}/></button><span>{selected.code} / 28 views</span><button aria-label="Next view" disabled={index<0||index===journey.steps.length-1} onClick={()=>go(journey.steps[index+1])}><ChevronRight size={18}/></button></div></div><aside className="handoff-panel"><div className="handoff-label">For Irina & Kerem</div><h2>{selected.subtitle}</h2><p>{selected.description}</p><div className="implementation-note"><b>Production connection</b><p>{selected.backend}</p></div>{['pending','gift-received','provisioning'].includes(view)&&<label className="scenario"><span>Review another state</span><select value={scenario} onChange={e=>setScenario(e.target.value)}><option value="default">Standard path</option>{view==='gift-received'?<><option value="locked">Transfer locked</option><option value="pending">Owner validation pending</option></>:<><option value="failure">Failure / recovery</option>{view==='pending'&&<option value="pending">Still pending</option>}</>}</select></label>}<div className="handoff-links"><a href={SOURCE} target="_blank" rel="noopener">Compare with Irina’s screens <ArrowUpRight size={14}/></a><a href="/mobile/implementation.md" target="_blank" rel="noopener">Source & import instructions <ArrowUpRight size={14}/></a><a href="/delivery#checklist">Delivery checklist <ArrowUpRight size={14}/></a></div><p className="small-note">This page adds browser-based React views. It is not a compiled iOS/Android app and does not imply a specific native installation API.</p></aside></div>}
  </section><section className="mobile-close"><div><p className="eyebrow">An extension, not a replacement</p><h2>Keep the identity.<br/>Finish the journeys.</h2><p>Use these views alongside Irina’s original app delivery. Retain the current product rules, wire real server states, and verify every journey on the target devices.</p></div><div><a className="lab-button primary" href="/delivery">Back to the full delivery <ArrowRight size={17}/></a><a href="/mobile/catalog.json" target="_blank" rel="noopener">View the screen inventory</a><a href="/mobile/changelog.md" target="_blank" rel="noopener">Read the additions log</a></div></section></main><footer className="lab-footer"><Brand/><span>Openline Mobile · 28 extra views · October 2026</span><a href={SOURCE} target="_blank" rel="noopener">Original reference <ArrowUpRight size={14}/></a></footer>{notice&&<div className="lab-toast" role="status">{notice}</div>}</>;
}
createRoot(document.getElementById('root')).render(<App/>);
