// Checked against the public revisions site on 9 October 2026.
// Observations are scoped, not a claim that the entire site passed an audit.
const revision=slug=>'https://openline-revisions-hub.vercel.app/'+slug;
const reference=slug=>'https://openline-anims-review.vercel.app/qa/'+slug;
export const PALETTE_REVIEW=[
  {slug:'blog',title:'Blog',name:'Newsprint',hex:'#111111',swatches:['#111111','#6B6B6B','#FBFAF7'],status:'gap',finding:'Headline accent, badges and statistics are still orange; QA uses a monochrome editorial treatment.',action:'Apply the Newsprint page identity to headings, badges, icon tiles, cards, backgrounds and selected artwork. Preserve the orange actions that the QA reference deliberately retains.'},
  {slug:'network',title:'Network',name:'Corporate blue',hex:'#1E40AF',swatches:['#1E3A8A','#1E40AF','#2563EB'],status:'gap',finding:'The headline accent and feature statistics still use #FF5314 instead of the blue/navy QA identity.',action:'Bring across the blue headings, navy ink, section washes, cards and Network HUD treatment. Importing the illustration alone is not the complete page change.'},
  {slug:'security',title:'Security',name:'Vault teal',hex:'#0F766E',swatches:['#134E4A','#0F766E','#14B8A6'],status:'gap',finding:'“Online Threats”, the metrics and repeated page accents remain orange.',action:'Use the teal palette across the page and its existing illustrations, with green status signals kept distinct.'},
  {slug:'adblocking',title:'AdBlocking',name:'Ultraviolet',hex:'#6D28D9',swatches:['#4C1D95','#6D28D9','#8B5CF6'],status:'gap',finding:'“Save Data”, the headline statistics and section accents remain orange.',action:'Apply the violet page identity to headings, badges, icon treatments, charts and tinted surfaces, matching the QA page in context.'},
  {slug:'unlimited',title:'Unlimited',name:'Hot magenta',hex:'#DB2777',swatches:['#831843','#DB2777','#F472B6'],status:'gap',finding:'Updated promise/profile-replacement copy is present, but the heading, metrics and accents are still orange.',action:'Keep the revised fixed/unlimited policy copy and apply the magenta identity. Preserve the intentionally neutral usage cards and the explicit local-network caveat.'},
  {slug:'iot',title:'IoT',name:'Chrome',hex:'#6B7280',swatches:['#1F2329','#6B7280','#D1D5DB'],status:'seen',finding:'The three mounted illustrations now show neutral steel/gunmetal treatment. This is not another “still orange” gap.',action:'Retain Chrome as default and finish the full responsive comparison. Orange Openline branding and meaningful green online states are intentional exceptions.'},
  {slug:'global-esim',title:'Global eSIM',name:'Openline orange',hex:'#FF5314',swatches:['#FF5314','#FFB08F','#FFF3EB'],status:'seen',finding:'The sampled headings and accents are orange, which is the intended identity for this page.',action:'Keep the orange-only page treatment and verify every remaining box/illustration. Do not restore mixed blue, purple or green decorative sections, or recolour actual partner logos.'},
].map(p=>({...p,current:revision(p.slug),target:reference(p.slug)}));
export const FOLLOWUP_TASKS=[
  ...PALETTE_REVIEW.map(p=>({id:'followup-20261009-palette-'+p.slug,title:`9 Oct · ${p.title}: ${p.name}`,pages:[p.slug],type:'9 October follow-up',description:`${p.status==='gap'?'Confirmed palette gap.':'Observed at sampled points; final verification still required.'} ${p.finding} ${p.action}`,route:'/delivery#follow-up',files:['qa/core.js','qa/recolor.js','qa/paint.js'],review:false})),
  {id:'followup-20261009-france-layout',title:'9 Oct · Finish the France Unlimited block',pages:['country-fr-redesign'],type:'9 October follow-up',description:'Keep the original France page and fixed Data Bundles. Match the QA Unlimited block: full-width balanced date/day row, “or number of days”, “Popular durations”, aligned number-only duration tiles, selected shadow, price/features and CTAs. The current narrow, heavier-bordered controls row is not the final QA block. Keep the already imported calendar and fair-use modal.',route:reference('country-fr-redesign')+'#fr-plans',files:['qa/country-fr-refinement.css','qa/country-fr-refinement.js'],review:false},
  {id:'followup-20261009-france-promise',title:'9 Oct · Remove France’s contradictory no-throttling headline',pages:['country-fr-redesign'],type:'9 October follow-up',description:'Replace “All plans include unlimited speed with no throttling” with “Fixed packages: no usage-based throttling. Unlimited plans: local network fair use applies.” Keep “Perfect for heavy users. Stream, video call, and browse without limits.” as the Unlimited introduction and retain its separate fair-use disclosure.',route:revision('country-fr'),files:['qa/country-fr-changelog.md'],review:false},
  {id:'followup-20261009-mobile-master',title:'9 Oct · Merge all mobile views into Irina’s master visual system',pages:['mobile'],type:'9 October follow-up',description:'The 28 extra workflows are linked from app-screens, but common technology is not visual parity. Measured payment CTA: master 16px/24px with 16px vertical padding; extension 14px/19.6px with 12px vertical padding. Use the original app screens as master for component sizes, type, spacing, surfaces, shadows, cards, headers and navigation. Final mobile selection/build handoff remains on hold until harmonised; do not ask Kerem to choose between two competing themes.',route:'https://openline-revisions-hub.vercel.app/app-screens',files:['mobile/implementation.md','mobile-src/src/style.css'],review:false},
  {id:'followup-20261009-help-composer',title:'9 Oct · Port and verify the help-composer resize fix',pages:['chat'],type:'9 October follow-up',description:'Paul’s “Typeform” screenshot shows the chat message composer, not a verified third-party Typeform embed. After resizing the public modal, textarea height measured 24px against 45px scroll content (24.65px line-height + 20px padding), reproducing the clipping. Import the min-height/box-sizing floor and padding-aware, resize-aware autosize fix from this pack. Test empty, one line, multiline, sidebar open/closed, viewport changes, zoom and mobile keyboard; do not submit real support requests during visual QA.',route:'https://snap.paulfleury.com/YdlXYxrW',files:['qa/support/chat.js','qa/support/support.css'],review:false},
  {id:'followup-20261009-login-port',title:'9 Oct · Apply the light-neutral login-icon tile',pages:['login'],type:'9 October follow-up',description:'Preserve Globe & Pin option 6 and its animation. Replace the orange tile with #F3F4F6 and a subtle #E5E7EB inset edge. Use the updated QA/login and portable delivery preview; do not replace the selected glyph or recolour the entire login page.',route:reference('login'),files:['qa/qa.css','delivery/runtime/animation.css'],review:false},
  {id:'followup-20261009-figma',title:'Final return · Editable Figma master',pages:['delivery'],type:'9 October follow-up',description:'Provide an accessible editable Figma link/file with the final website, panel/cart and unified mobile components, variants and states. Identify the final master, remove competing alternatives from the production handoff, and confirm access for Paul and Kerem. This review has not verified receipt of that final file.',route:'/delivery#follow-up',review:true},
  {id:'followup-20261009-react',title:'Final return · Matching React source',pages:['delivery'],type:'9 October follow-up',description:'Provide the integrated React source with package.json, lockfile, assets, component/page mapping, build commands and revision/commit. It must match the final staging build and Figma, not just the separate AI reference source in this pack.',route:'/delivery#follow-up',review:true},
  {id:'followup-20261009-zip',title:'Final return · Versioned final ZIP',pages:['delivery'],type:'9 October follow-up',description:'Supply one dated/versioned ZIP containing the final source, assets and documentation. Verify a clean install/build and include staging/build references. This site’s reference ZIP is provided for integration; it is not evidence that Irina’s integrated final ZIP has been delivered.',route:'/delivery#follow-up',review:true},
  {id:'followup-20261009-markdown',title:'Final return · Change log and handoff Markdown',pages:['delivery'],type:'9 October follow-up',description:'Document what changed in animations, palette, layout, wording, interactions, modals, app screens and small details; list source paths, decisions, outstanding backend work and QA evidence. Return completion status for every delivery item with links, screenshots and blockers.',route:'/delivery#follow-up',review:true},
];
