/* The implemented QA surface, not production approval. Keep this registry
   in sync with code so page panels and the global handoff share one account.
   Never add user-entered codes, chat transcripts or clipboard content here. */
export const QA_CHANGES = [
  { id: 'native-typography', title: 'Openline typography everywhere', pages: ['*'], status: 'Implemented in QA', route: '/qa',
    summary: 'One native Openline UI font stack across captured pages, retained redesigns, animations, navigation, chat, help and modal tools.',
    delivery: 'Play is reserved for the wordmark; monospace remains only for genuine code and technical fields. Original review-board typography is unchanged.' },
  { id: 'context-fit', title: 'Animation fit and background coherence', pages: ['*'], status: 'Implemented in QA', route: '/qa',
    summary: 'Animations are evaluated inside measured page slots, with responsive sizing, background clearing and panel warnings for remaining aspect-ratio mismatches.',
    delivery: 'Retain the chosen animation concepts. A panel fit warning is an unresolved review item, not an automatic production approval.' },
  { id: 'page-browser', title: 'Quick page dropdown', pages: ['*'], status: 'Implemented in QA', route: '/qa',
    summary: 'The bottom page label opens a searchable, keyboard-accessible menu for 20 page entries plus four extra tools.',
    delivery: '18 original pages and the retained About / Contact alternatives. The later 16-page alternative batch was removed and must not be delivered.' },
  { id: 'home-why-fit', title: 'Why Openline: context-sized artwork', pages: ['home'], status: 'Implemented in QA', route: '/qa/home',
    summary: 'Option 3 is fitted to the 407 × 302 home slot, with readable content and without the board wrapper competing with the page.',
    delivery: 'Use the actual slot geometry rather than stretching the nominal board canvas.' },
  { id: 'referral-fit', title: 'Referral: one orange, a softer edge', pages: ['home'], status: 'Implemented', route: '/qa/home',
    summary: 'Referral option 3 matches the original orange, fits its 576 × 520 slot and keeps the selected animation. Background plus signs fade smoothly from 0% on the left to full treatment on the right.',
    delivery: 'The shared option also fixes the original review board. Preserve its motion and transparent integration with the surrounding block.' },
  { id: 'page-identities', title: 'Page-specific colour treatments', pages: ['network', 'security', 'adblocking', 'unlimited', 'blog'], status: 'Review options', route: '/qa',
    summary: 'Network blue, Security teal, AdBlocking ultraviolet, Unlimited magenta and Blog newsprint are switchable within each page.',
    delivery: 'The export includes each identity’s current on/off state and the global theme. Do not treat these proposals as approved production defaults.' },
  { id: 'iot-chrome', title: 'IoT: selected Chrome default', pages: ['iot'], status: 'Selected default', route: '/qa/iot',
    summary: 'Purple and indigo accents become neutral steel, graphite and gunmetal with a restrained chrome sheen.',
    delivery: 'Chrome starts selected. Keep orange branding and green online status meaningful; honour the reviewer’s explicit identity toggle.' },
  { id: 'nomad-stability', title: 'Openline+: steady destination labels', pages: ['openline-plus'], status: 'Implemented in QA', route: '/qa/openline-plus',
    summary: 'Built for Digital Nomads no longer repeatedly fades its city labels. Connection motion continues and the number is the fictional US example +1 202 555 0148.',
    delivery: 'Context-only refinement of Six Cities, One Number. The original board remains a comparison reference.' },
  { id: 'about-layout', title: 'Retained About redesign', pages: ['about', 'about-redesign'], status: 'QA alternative', route: '/qa/about-redesign',
    summary: 'The earlier About redesign remains available beside the original, including its principles, team presentation, local clocks and partner strip.',
    delivery: 'Preserve current/original comparison. Illustrative business claims require content approval before shipping.' },
  { id: 'about-network-spacing', title: 'Network comparison: corrected card spacing', pages: ['about-redesign'], status: 'Implemented in QA', route: '/qa/about-redesign#rd-network-technology',
    summary: 'The two Most Reliable Connection cards have consistent inset padding, clear title-to-list spacing and aligned icon/bullet rows. Comparison titles use scoped heading styles instead of inheriting generic paragraph margins and sizing.',
    delivery: 'Desktop and mobile spacing are explicit. The two network illustrations and their animation timings are unchanged; original About remains a comparison reference.' },
  { id: 'about-startup-locked', title: 'Open Startup: locked coming-soon results', pages: ['about-redesign'], status: 'Coming very soon', route: '/qa/about-redesign#rd-open-startup',
    summary: 'Open Startup now explains that public results are coming very, very soon. A lock notice and keyboard-operable Show / Hide results preview control replace the previous live-looking sample metrics.',
    delivery: 'Expanded by default, as selected by Paul. All three dashboard cards retain locked placeholders only, not financial figures; the Hide / Show control remains available. Prior sample revenue, margin, growth, active-user and retention numbers and Live badges were removed from this section, not merely blurred. No metrics API or publication date is implied.' },
  { id: 'about-team-cities', title: 'Team roster: nine supplied locations', pages: ['about-redesign'], status: 'Implemented in QA', route: '/qa/about-redesign',
    summary: 'The local-time roster now lists New York, Lisbon, Warsaw, Ankara, Bristol, Berlin, Paris, Singapore and Bali in the supplied order, with city badges instead of fictional staff initials.',
    delivery: 'Nine locations, one team replaces the old six-timezone claim. Clocks use IANA zones with daylight-saving rules where applicable; Ankara uses Europe/Istanbul, Bristol Europe/London and Bali Asia/Makassar. The currently selected team animation remains unchanged.' },
  { id: 'redesign-button-parity', title: 'Redesign buttons: native type and arrow motion', pages: ['about-redesign', 'contact-redesign'], status: 'Implemented in QA', route: '/qa/about-redesign',
    summary: 'About and Contact action buttons use the current Openline type scale and icon sizing: 16px / 24px, weight 500 for main actions; 14px compact contact actions and mobile purchase CTAs; 16px button icons. Trailing arrows match the source shape and slide 4px over 150ms without shifting the text or lifting the button.',
    delivery: 'Verified against live Openline and the original capture. Arrow motion responds to hover, keyboard focus and press, with a static reduced-motion fallback. Keep 8px corners, 8px base gaps, source-like desktop heights and at least 44px mobile tap targets. Purchase CTAs use the source-style Buy eSIM Now label on small screens, keeping the existing 190+ country count. No arrow motion is applied to chat symbols or disclosure/FAQ chevrons. Page layouts and selected illustration animations are preserved.' },
  { id: 'contact-layout', title: 'Retained Contact redesign', pages: ['contact', 'contact-redesign'], status: 'QA alternative', route: '/qa/contact-redesign',
    summary: 'The earlier Contact redesign remains alongside the original, with contact methods, support process, chat preview and global support block.',
    delivery: 'Only this retained Contact alternative receives the latest channel/widget redesign; the original capture is a comparison reference.' },
  { id: 'contact-channels', title: 'Contact channels and future hotline', pages: ['contact-redesign', 'chat'], status: 'Implemented / hotline coming soon', route: '/qa/contact-redesign',
    summary: 'WhatsApp +1 (555) 484-2461; Instagram and Messenger/Facebook @askopenline; email ask@openline.com. The Contact page adds a Live hotline widget below 24/7 Global Support: +1 (8) 123 - ONLINE.',
    delivery: 'WhatsApp https://wa.me/15554842461; Instagram https://www.instagram.com/askopenline/; Messenger https://m.me/askopenline; Facebook https://www.facebook.com/askopenline; mailto:ask@openline.com. Hotline is visibly Coming soon, has no dial action, and is not an operational number.' },
  { id: 'contact-chat-seeking', title: 'Clickable support-process animation', pages: ['contact-redesign'], status: 'Implemented in QA', route: '/qa/contact-redesign',
    summary: 'Each of the three How Our Chat Support Works steps seeks its matching animation scene. Automatic playback continues and highlights follow the SVG clock.',
    delivery: 'Keyboard-operable buttons with pressed state. Reduced-motion pauses autoplay but preserves manual scene selection.' },
  { id: 'installation-preflight', title: 'Installation preflight and roadmap', pages: ['installation-guide'], status: 'Targeted QA redesign', route: '/qa/installation-guide',
    summary: 'Only the purchase-code-to-profile explainer and four-step How this page works strip were redesigned, with a clear code/profile distinction, compatibility action and real section anchors.',
    delivery: 'The selected animation and all surrounding captured HTML stay intact. Redeem links to the /qa/start prototype. Reconcile activation-policy copy before production: the existing installation guide still says activate at destination, whereas the requested /start prototype starts validity immediately.' },
  { id: 'start-flow', title: 'Purchase code to eSIM extra', pages: ['start', 'installation-guide'], status: 'Interactive prototype', route: '/qa/start',
    summary: 'Animated key, large GAZE19-MULCH29-NYMPH13-format input, code validation, sample purchase review, gift/copy flow, account path, explicit activation confirmation and animated eSIM-profile reveal.',
    delivery: 'Checking does not activate. Confirmation says validity starts immediately, gifting ends, and later travellers should wait; unchecked readiness is mandatory. Includes invalid/used/network/provisioning-error states, reduced motion and safe cancellation. All plan/code/profile data are fixtures: no provisioning API, real account action, persistent code storage or installable QR.' },
  { id: 'start-profile-handoff', title: 'Complete activation: details, setup, organisation', pages: ['start'], status: 'Interactive prototype', route: '/qa/start',
    summary: 'The final eSIM stage opens a three-step handoff: QR and manual installation details; existing setup/connection guidance for iPhone, Samsung and Pixel/Android; optional label and folder, then a completion screen with Go to my account. Includes copyable SM-DP+ address, activation code, full LPA string, ICCID and Openline profile ID, plus an explicitly unlinked EID state.',
    delivery: 'ICCID identifies the profile; EID identifies the device eSIM chip, so no EID is fabricated. The demo QR encodes a harmless notice, not installation data, and the server address uses .invalid. Label/folder and custom-folder creation are saved only in this browser tab, with honest fallback if storage fails; no code or credentials enter storage. Account continues to /qa/login, not a connected account API. Setup reuses existing KB guidance and links to the unchanged installation guide/animation; no device installation or connectivity is claimed.' },
  { id: 'modal-builder', title: 'Expanded modal builder', pages: ['modals'], status: 'Interactive tool', route: '/qa/modals',
    summary: 'Eight types, 60 Openline templates, 358 animated icons, 16 content-block types, custom images, one/two actions and real-page backdrop preview.',
    delivery: 'The builder keeps its own detailed HTML / Copy for Computer export for the active draft. Global export inventories the capability; export the modal draft separately when handing it off.' },
  { id: 'chat-sidebar-ai', title: 'Chat sidebar and AI handoffs', pages: ['chat'], status: 'Interactive prototype', route: '/qa/chat',
    summary: 'Full-height collapsed rail opens on any tap/click; rail arrow, expanded-panel arrow and header icon toggle it. Nine editable prompts and seven AI providers use real locally hosted logos/favicons.',
    delivery: 'Each AI opens a copy-and-handoff dialog, reports clipboard success/failure accurately and uses its official web interface via a new-tab HTTPS link. No prompt URL parameters or automatic transcript sharing; installed-app handling is device-dependent, not guaranteed.' },
  { id: 'chat-fresh-clear', title: 'Fresh guest welcome and Clear chat', pages: ['chat'], status: 'Interactive prototype', route: '/qa/chat',
    summary: 'Animated welcome icon and Gary’s How can I help you? greeting appear for a new guest or after confirmed Clear chat. Text, files, voice, local history and simulated replies remain.',
    delivery: 'Confirmation describes the intended live server deletion / issue-solved behaviour, with explicit QA-only disclosure. This demo clears only local history and attachments. Outstanding replies and recordings are cancelled so old content cannot return; backend deletion and ticket closure are not implemented.' },
  { id: 'chat-brand-portraits', title: 'Chat: official mark and centred profile portraits', pages: ['chat'], status: 'Implemented in QA', route: '/qa/chat',
    summary: 'The chat header, animated welcome and Gary avatar use the actual Openline mark already sourced for /start. Seven circular photo portraits form one centred row directly above Here to help you stay connected, in both the fresh welcome and conversation intro.',
    delivery: 'CC0 demo portraits are hosted locally and labelled illustrative, not actual staff identities or online availability. Their order is shuffled once when opening chat and remains stable through messages, replies and clearing. The row is centred within the conversation area, including when the side panel changes width. Gary’s brand avatar remains visible on mobile.' },
  { id: 'help-modals', title: 'Knowledge base and device checker', pages: ['kb', 'chat', 'installation-guide', 'start'], status: 'Interactive QA tools', route: '/qa/kb',
    summary: 'Searchable help and compatibility modals use the included 2,737-article and 9,496-device datasets, shared launchers, keyboard controls and deep-link states.',
    delivery: 'Keep dataset provenance and refresh needs in the final handoff. Search results do not turn the separate chat or redemption prototypes into connected production services.' },
  { id: 'qa-reporting', title: 'Non-animation change reporting', pages: ['*'], status: 'Implemented in QA', route: '/qa#qa-changes',
    summary: 'Page panels show relevant changes and shared refinements, with persistent page-level notes. The hub lists every implemented item; Copy for Computer includes the full inventory and machine-readable v3 data.',
    delivery: 'Animation-pick deltas are counted separately from implemented refinements. Resets preserve page-level notes and this inventory. No /delivery is created yet; no chat transcripts or entered purchase codes are exported.' },
];

export const changesForPage = slug => QA_CHANGES.filter(c => c.pages.includes('*') || c.pages.includes(slug));
const safe = s => String(s).replace(/[&<>"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;' }[c]));
export function changeCards(changes) {
  return changes.map(c => `<details class="qa-change" data-change-id="${c.id}"><summary><span><b>${safe(c.title)}</b><small>${safe(c.status)}</small></span></summary><div><p>${safe(c.summary)}</p><p class="qa-change-delivery"><b>Handoff:</b> ${safe(c.delivery)}</p><a href="${c.route}">Review in /qa →</a></div></details>`).join('');
}
export function changesMarkdown() {
  return ['## Page, interaction and tooling changes', '',
    'These are implemented QA refinements or explicitly labelled prototypes, not production approval. They are independent of animation-pick deltas.', '',
    ...QA_CHANGES.flatMap(c => [`### ${c.title}`, `- ID: \`${c.id}\` · ${c.status} · ${c.route}`,
      `- Scope: ${c.pages.includes('*') ? 'Shared /qa' : c.pages.join(', ')}`,
      `- Implemented: ${c.summary}`, `- Handoff: ${c.delivery}`, '']),
    '## Review decisions', '',
    '- Keep only the previous About and Contact redesigns. The rejected later batch of 16 alternatives is removed.',
    '- Finish /qa first. A separate /delivery and its documentation have not been requested for execution yet.',
    '- QA examples, marketing claims and activation-policy differences still need product/content approval before production.',
    ''].join('\n');
}
