// Generated by qa/tools/connectivity_copy.py from connectivity-copy.json.
export const CONNECTIVITY_COPY = {
  "multiple-tier1": [
    {
      "area": "Hero badge",
      "before": "AI-Powered Multi-Network",
      "after": "Adaptive Multi-Network"
    },
    {
      "area": "Hero introduction",
      "before": "Unlike competitors who lock you to a single provider, Openline uses AI to automatically switch between multiple premium Tier-1 networks - delivering both the best signal and lowest prices, always.",
      "after": "Openline is not tied to one underlying provider. We can adapt the networks available on your current eSIM or, when needed, issue another profile to move you to a different provider and connectivity setup. Profile replacement should be uncommon, but it is part of how we work to keep your service performing well."
    },
    {
      "area": "Infrastructure heading",
      "before": "What is a Tier-1 Network?",
      "after": "The networks behind your connection"
    },
    {
      "area": "Infrastructure explanation",
      "before": "A Tier-1 network operator is a historic or national carrier that owns and operates the physical antenna infrastructure at ground level. Unlike resellers who just rent capacity, Tier-1 operators built and maintain the actual towers and antennas that provide mobile coverage.",
      "after": "Your connection relies on a mobile network, an underlying connectivity provider and the eSIM profile on your phone. Access to established operators gives us more options, while the ability to replace a profile lets us change the service setup behind it when that is the better route."
    },
    {
      "area": "Infrastructure card",
      "before": "Historic Operators",
      "after": "Established Operators"
    },
    {
      "area": "Infrastructure card",
      "before": "National carriers who built the actual antennas and towers",
      "after": "Established mobile networks in the destinations we serve"
    },
    {
      "area": "Infrastructure card",
      "before": "Antenna Ownership",
      "after": "Network Infrastructure"
    },
    {
      "area": "Infrastructure card",
      "before": "Own and maintain physical network, not just resell",
      "after": "The radio network is one part of your connectivity setup"
    },
    {
      "area": "Quality card",
      "before": "Best signal, fastest speeds, most reliable",
      "after": "Service options chosen for local coverage and performance"
    },
    {
      "area": "Coverage card",
      "before": "Complete infrastructure in remote and urban areas",
      "after": "Coverage depends on your destination, device and available partners"
    },
    {
      "area": "Why the network matters",
      "before": "Tier-1 operators like Vodafone, T-Mobile, and Orange own the physical infrastructure, giving them direct control over signal quality, network capacity, and coverage. This means better speeds, stronger signals, and more reliable connections compared to virtual operators who only resell capacity.",
      "after": "A strong local network matters, but it is not the whole picture. If the provider or configuration behind a profile is no longer a good fit, changing the network alone may not be enough. We can issue a replacement eSIM to move the service to a different setup."
    },
    {
      "area": "Partner introduction",
      "before": "Featured partners from our network of 200+ Tier-1 operators worldwide",
      "after": "Examples from our wider operator ecosystem. Available networks depend on your profile, plan and destination."
    },
    {
      "area": "Partner caption",
      "before": "Featured operators from 200+ Tier-1 network partners with their own infrastructure",
      "after": "Carrier and connectivity-partner examples; availability varies by location and profile"
    },
    {
      "area": "Regional introduction",
      "before": "In addition to global Tier-1 operators, we partner with leading regional carriers to ensure exceptional coverage in every market",
      "after": "Global and regional partners give us different ways to deliver service. A replacement profile can open a different provider setup where your current profile is not the right fit."
    },
    {
      "area": "Regional selection heading",
      "before": "AI Selects the Best Network Automatically",
      "after": "Network selection is only one part of the service"
    },
    {
      "area": "Regional selection explanation",
      "before": "Whether you're connecting through Vodafone in London, MTN in Johannesburg, du in Dubai, China Mobile in Shanghai, or giffgaff for value roaming - our AI continuously evaluates all available partners to ensure you always get the optimal combination of signal quality and pricing. You never need to manually choose or configure anything.",
      "after": "We look for a suitable service path among the options available to your plan and location. Usually that means using your current eSIM profile. Occasionally, a better option means issuing a new profile and changing the underlying provider. If installation or activation is needed on your phone, we will guide you through that step."
    },
    {
      "area": "Selection introduction",
      "before": "Our advanced machine learning algorithms continuously analyze signal strength, network congestion, and real-time pricing data to automatically connect you to the optimal Tier-1 network every second.",
      "after": "Our selection approach considers connection quality, congestion and provider options. We can change networks within the current profile where supported, or replace the profile when a different underlying service setup is needed."
    },
    {
      "area": "Selection card",
      "before": "Machine learning analyzes signal strength, congestion, and pricing in real-time.",
      "after": "Connection quality, congestion and pricing inform the service options we consider."
    },
    {
      "area": "Selection card",
      "before": "Continuously monitor all networks and switch when better options appear.",
      "after": "Adapt to the network options available to your current profile, plan and location."
    },
    {
      "area": "Selection card",
      "before": "Track wholesale prices to route you through the most cost-effective option.",
      "after": "Consider provider pricing alongside the quality and availability of the connection."
    },
    {
      "area": "Switching card heading",
      "before": "Instant Switching",
      "after": "Profile Flexibility"
    },
    {
      "area": "Switching card explanation",
      "before": "Seamless transitions in milliseconds - you won't even notice when it happens.",
      "after": "When a network switch is not enough, we can issue another eSIM profile. A setup step or reconnection may be needed."
    },
    {
      "area": "Market introduction",
      "before": "Mobile data operates like a stock market - prices fluctuate constantly based on demand, network capacity, and market conditions. Our proprietary OMDM™ (Openline Mobile Data Market) platform trades this market 24/7 with AI to secure the lowest wholesale prices and pass the savings directly to you.",
      "after": "Provider pricing and service conditions can change. OMDM™ (Openline Mobile Data Market) helps us compare the options behind your connection. If a more suitable option uses a different provider or profile configuration, we may issue a new eSIM rather than keep you on the same service setup."
    },
    {
      "area": "Market benefit",
      "before": "Our AI continuously monitors these price fluctuations to purchase data at the lowest possible rates, 24/7.",
      "after": "Compare available provider offers alongside service quality, rather than choose on price alone."
    },
    {
      "area": "Market benefit",
      "before": "We pass these wholesale savings directly to customers, ensuring you always get the cheapest prices.",
      "after": "Provider flexibility helps us balance value and usable service. It is not a guarantee of the cheapest price at every moment."
    },
    {
      "area": "Market benefit",
      "before": "Our algorithms execute thousands of data purchases daily across different networks and regions to optimize pricing.",
      "after": "A service change can happen within your current profile or, occasionally, through a replacement profile on a different provider setup."
    },
    {
      "area": "How it works introduction",
      "before": "Real-time optimization in three simple steps to ensure you always have the best connection.",
      "after": "Review the available options, choose a suitable service path, then adapt the network or the whole profile when needed."
    },
    {
      "area": "Monitor step",
      "before": "Scan all available Tier-1 networks every second for signal strength and performance metrics.",
      "after": "Review connection conditions and the service options available to your plan and location."
    },
    {
      "area": "Analyze step",
      "before": "AI evaluates signal quality, congestion levels, and wholesale pricing data in real-time.",
      "after": "Consider connection quality, congestion, provider options and pricing together."
    },
    {
      "area": "Adapt step heading",
      "before": "Switch",
      "after": "Adapt"
    },
    {
      "area": "Adapt step",
      "before": "Automatically connect to the optimal network for best performance and lowest cost.",
      "after": "Use a suitable network on the existing profile, or issue a replacement eSIM to change the underlying provider and setup."
    },
    {
      "area": "Access introduction",
      "before": "We partner with the world's leading mobile network operators to provide you with unmatched coverage, speed, and reliability across 190+ countries - all powered by AI.",
      "after": "Our partner ecosystem gives us several ways to deliver connectivity. Access depends on your plan, destination and eSIM profile; not every network is available on every profile. Where necessary, we can issue a new profile to move you to a different service setup."
    },
    {
      "area": "Access checklist",
      "before": "Always connected to the strongest available signal",
      "after": "Choose among suitable, available network options"
    },
    {
      "area": "Access checklist",
      "before": "AI automatically selects best network every second",
      "after": "Consider service quality, availability and value"
    },
    {
      "area": "Access checklist",
      "before": "Access to 50+ premium Tier-1 network partners",
      "after": "Access varies across our 50+ Tier-1 partner ecosystem"
    },
    {
      "area": "Access checklist",
      "before": "Seamless handoffs between networks",
      "after": "Network changes within a supported profile"
    },
    {
      "area": "Access checklist",
      "before": "Lower prices through intelligent market analysis",
      "after": "Provider choices informed by market conditions"
    },
    {
      "area": "Access checklist",
      "before": "Better performance in congested areas",
      "after": "Alternative service paths when performance suffers"
    },
    {
      "area": "Access checklist",
      "before": "Reduced dead zones and coverage gaps",
      "after": "Profile replacement when a different setup is needed"
    },
    {
      "area": "Access checklist",
      "before": "No manual configuration ever needed",
      "after": "Guided installation if a new profile is required"
    },
    {
      "area": "Closing headline",
      "before": "Experience AI-Powered Connectivity",
      "after": "Connectivity that can adapt"
    },
    {
      "area": "Closing introduction",
      "before": "Join thousands of travelers who never worry about connectivity. Get access to multiple Tier-1 networks with AI-powered switching for the best signal and lowest prices.",
      "after": "Choose a plan backed by more than one service option. We can adapt the network where supported and occasionally replace the eSIM profile to move you to a better underlying setup."
    },
    {
      "area": "Closing badge",
      "before": "Best signal always",
      "after": "Adapt to local conditions"
    },
    {
      "area": "Closing badge",
      "before": "Lowest prices",
      "after": "Quality and value"
    },
    {
      "area": "Closing badge",
      "before": "No manual switching",
      "after": "Profile changes may apply"
    }
  ],
  "unlimited": [
    {
      "area": "Hero badge",
      "before": "Truly Unlimited",
      "after": "No Throttling from Openline"
    },
    {
      "area": "Hero heading",
      "before": "Unlimited Speed,No Limits",
      "after": "Your data. Full speed. Our promise, explained."
    },
    {
      "area": "Hero introduction",
      "before": "No throttling. No fair usage policy. No hidden limits. When we say unlimited, we mean it. Use your full data allocation at full speed, always.",
      "after": "Buy 10 GB and get all 10 GB at full speed, guaranteed, with no usage-based throttling. Openline adds no data cap or throttling to unlimited plans either, but the local mobile operator’s fair-use rules can still reduce their speed after heavy use."
    },
    {
      "area": "Meaning heading",
      "before": "What Unlimited Really Means",
      "after": "One promise. Two types of plan."
    },
    {
      "area": "Meaning introduction",
      "before": "While other providers use \"unlimited\" as a marketing term, Openline delivers genuinely unlimited data at full speed with zero throttling or hidden restrictions.",
      "after": "On a fixed-data package, your entire purchased allowance is guaranteed at full available network speed, without usage-based throttling. On an unlimited plan, Openline imposes no data cap or throttling, but local operator fair-use rules still apply. Full speed means the speed the network can deliver: signal, congestion and your device can affect it."
    },
    {
      "area": "Feature heading",
      "before": "No Speed Throttling",
      "after": "10 GB means all 10 GB"
    },
    {
      "area": "Feature copy",
      "before": "Full speed from the first byte to the last. Your connection never slows down, no matter how much you use.",
      "after": "Buy a 10 GB package and every GB is available at full speed. We guarantee no usage-based throttling anywhere within your purchased allowance."
    },
    {
      "area": "Feature heading",
      "before": "No Fair Usage Policy",
      "after": "Unlimited on our side"
    },
    {
      "area": "Feature copy",
      "before": "Truly unlimited means unlimited. Use your full data allocation without any hidden restrictions.",
      "after": "For unlimited plans, we guarantee that Openline adds no data cap or usage-based speed restriction. The local mobile network operator’s rules are a separate matter."
    },
    {
      "area": "Feature heading",
      "before": "4K Streaming Ready",
      "after": "Local network fair use"
    },
    {
      "area": "Feature copy",
      "before": "Stream in the highest quality without buffering. Perfect for Netflix, YouTube, and video calls.",
      "after": "On unlimited plans, using a lot of data quickly within 24 hours may trigger a local MNO fair-use policy and temporarily reduce your speed. Thresholds and recovery times vary by network and plan."
    },
    {
      "area": "Feature heading",
      "before": "Consistent Performance",
      "after": "Want no throttling? Go fixed."
    },
    {
      "area": "Feature copy",
      "before": "Same high speed whether you're the first user or the millionth. No congestion, no slowdowns.",
      "after": "Choose a fixed-data package if avoiding usage-based slowdowns is your priority. This is where we can guarantee your full purchased allowance at full available network speed."
    },
    {
      "area": "Usage introduction",
      "before": "See how Openline handles common use cases versus competitors",
      "after": "Streaming, downloads and backups can use a lot of data quickly. For guaranteed no-throttling access to your purchased allowance, choose a fixed package. Unlimited plans offer no Openline data cap, with local operator fair use still applying."
    },
    {
      "area": "Usage-card label",
      "before": "Others",
      "after": "Your use"
    },
    {
      "area": "Video example",
      "before": "Throttled to 480p after 5GB",
      "after": "Watch video at the quality your connection supports"
    },
    {
      "area": "Video example",
      "before": "Full 4K quality always",
      "after": "Fixed package: no usage-based slowdown"
    },
    {
      "area": "Download example",
      "before": "Speed reduced by 80%",
      "after": "Move the files you need for work or travel"
    },
    {
      "area": "Download example",
      "before": "Full speed guaranteed",
      "after": "All purchased GB at full speed"
    },
    {
      "area": "Calling example",
      "before": "Limited to 1 hour/day",
      "after": "Stay in touch through voice and video apps"
    },
    {
      "area": "Calling example",
      "before": "Unlimited HD calls",
      "after": "No Openline speed restriction"
    },
    {
      "area": "Backup example",
      "before": "Not allowed on mobile",
      "after": "Sync photos and backups on the go"
    },
    {
      "area": "Backup example",
      "before": "Upload without limits",
      "after": "Choose fixed for heavy uploads"
    },
    {
      "area": "Illustration badge",
      "before": "Full speed, always",
      "after": "No Openline throttling"
    },
    {
      "area": "Illustration label",
      "before": "buffering: none",
      "after": "quality varies"
    },
    {
      "area": "Service section kicker",
      "before": "Zero Restrictions",
      "after": "Choose with Confidence"
    },
    {
      "area": "Service section heading",
      "before": "Use Your Data Without Limits",
      "after": "Know your plan. Know our promise."
    },
    {
      "area": "Service section introduction",
      "before": "While other providers quietly throttle your speeds or impose usage restrictions, Openline delivers exactly what you paid for. Your full data allocation at full speed, every single time.",
      "after": "Fixed packages give you the clearest guarantee: all the data you buy, at full available network speed, without usage-based throttling. Unlimited plans have no cap or throttling added by Openline, but the local MNO may apply fair use. If that slows you down too often, we’ll try a replacement eSIM on another infrastructure with rules that better suit your location and usage."
    },
    {
      "area": "Service checklist",
      "before": "No speed throttling after certain usage",
      "after": "Fixed package: every purchased GB at full speed"
    },
    {
      "area": "Service checklist",
      "before": "No daily usage limits or caps",
      "after": "No usage-based throttling on fixed packages"
    },
    {
      "area": "Service checklist",
      "before": "No video quality restrictions",
      "after": "Unlimited: no data cap added by Openline"
    },
    {
      "area": "Service checklist",
      "before": "No 'fair usage policy' slowdowns",
      "after": "Unlimited: local MNO fair-use rules still apply"
    },
    {
      "area": "Service checklist",
      "before": "No time-of-day speed reductions",
      "after": "Heavy use within 24h may trigger a slowdown"
    },
    {
      "area": "Service checklist",
      "before": "No application-specific throttling",
      "after": "We’ll try another infrastructure if it happens often"
    },
    {
      "area": "Service checklist",
      "before": "No tethering/hotspot restrictions",
      "after": "Better fair use is our aim, not a guarantee"
    },
    {
      "area": "Service checklist",
      "before": "No peak-hour congestion",
      "after": "Guided setup if a replacement profile is needed"
    },
    {
      "area": "Usage illustration",
      "before": "NO CAP",
      "after": "LOCAL FUP MAY APPLY"
    },
    {
      "area": "Usage illustration",
      "before": "No throttling",
      "after": "No Openline cap"
    },
    {
      "area": "Usage illustration",
      "before": "No fair-use",
      "after": "Local fair use"
    },
    {
      "area": "Usage illustration",
      "before": "Full speed",
      "after": "Support if needed"
    },
    {
      "area": "Usage illustration",
      "before": "Unlimited speed",
      "after": "Unlimited from Openline"
    },
    {
      "area": "Closing headline",
      "before": "Experience True Unlimited",
      "after": "Your full allowance. Our full commitment."
    },
    {
      "area": "Closing introduction",
      "before": "Stop settling for throttled \"unlimited\" plans. Get genuinely unlimited speeds with Openline - use every MB at full speed.",
      "after": "Choose fixed data for guaranteed no-throttling access to every GB you buy. Choose unlimited for no Openline data cap, with local MNO fair-use rules still applying. If those rules limit you too often, we’ll try to find a better-fitting infrastructure for you."
    },
    {
      "area": "Closing badge",
      "before": "No limits",
      "after": "Fixed: full-speed data"
    },
    {
      "area": "Closing badge",
      "before": "Always reliable",
      "after": "Help with repeat slowdowns"
    },
    {
      "area": "Hero illustration",
      "before": "150 Mbps Download",
      "after": "Full-speed fixed data"
    },
    {
      "area": "Hero illustration",
      "before": "75 Mbps Upload",
      "after": "No Openline throttling"
    },
    {
      "area": "Hero illustration",
      "before": "12ms Latency",
      "after": "Local rules apply"
    },
    {
      "area": "Hero illustration",
      "before": "8.7 GB Used, No Throttling",
      "after": "Unlimited plans: local fair use may apply"
    },
    {
      "area": "Hero usage statistic",
      "before": "5X",
      "after": "∞"
    },
    {
      "area": "Hero usage statistic",
      "before": "Faster",
      "after": "Unlimited data"
    },
    {
      "area": "Hero flexibility statistic",
      "before": "0 · Throttling",
      "after": "0 · Fixed-plan throttling"
    },
    {
      "area": "Hero replacement frequency",
      "before": "24/7 · Always Fast",
      "after": "10 GB · All at full speed"
    }
  ]
};
export const UNLIMITED_PLAN_COPY = [
  {
    "area": "Hero badge",
    "before": "Unlimited Use, Adaptive Service",
    "after": "No Throttling from Openline"
  },
  {
    "area": "Hero heading",
    "before": "Unlimited usage. Service that adapts.",
    "after": "Your data. Full speed. Our promise, explained."
  },
  {
    "area": "Hero introduction",
    "before": "Our unlimited-use approach is built on flexibility, not one fixed connection. We can use another network where your profile supports it or, occasionally, issue a new eSIM profile to change the underlying provider and connectivity setup. Speeds still depend on local conditions.",
    "after": "Buy 10 GB and get all 10 GB at full speed, guaranteed, with no usage-based throttling. Openline adds no data cap or throttling to unlimited plans either, but the local mobile operator’s fair-use rules can still reduce their speed after heavy use."
  },
  {
    "area": "Meaning heading",
    "before": "Unlimited use needs a service that can adapt",
    "after": "One promise. Two types of plan."
  },
  {
    "area": "Meaning introduction",
    "before": "Our ability to move you to another eSIM profile is part of what supports unlimited use. If the current provider or service setup is no longer suitable, we can replace it rather than leave you stuck with it. Unlimited usage is not a promise of one constant speed everywhere.",
    "after": "On a fixed-data package, your entire purchased allowance is guaranteed at full available network speed, without usage-based throttling. On an unlimited plan, Openline imposes no data cap or throttling, but local operator fair-use rules still apply. Full speed means the speed the network can deliver: signal, congestion and your device can affect it."
  },
  {
    "area": "Fixed-package feature heading",
    "before": "Built for continued use",
    "after": "10 GB means all 10 GB"
  },
  {
    "area": "Fixed-package guarantee",
    "before": "Our aim is to keep your service usable as you use your plan. Network conditions and provider constraints can still affect performance.",
    "after": "Buy a 10 GB package and every GB is available at full speed. We guarantee no usage-based throttling anywhere within your purchased allowance."
  },
  {
    "area": "Openline-side feature heading",
    "before": "More than one service setup",
    "after": "Unlimited on our side"
  },
  {
    "area": "Openline-side promise",
    "before": "If your current service path stops being a good fit, we can issue another profile and move to a different underlying provider.",
    "after": "For unlimited plans, we guarantee that Openline adds no data cap or usage-based speed restriction. The local mobile network operator’s rules are a separate matter."
  },
  {
    "area": "Local-MNO feature heading",
    "before": "Streaming, calls and more",
    "after": "Local network fair use"
  },
  {
    "area": "24-hour heavy-use disclosure",
    "before": "Use your plan for the things you need on the move. Video quality and call performance depend on the connection available.",
    "after": "On unlimited plans, using a lot of data quickly within 24 hours may trigger a local MNO fair-use policy and temporarily reduce your speed. Thresholds and recovery times vary by network and plan."
  },
  {
    "area": "Plan recommendation heading",
    "before": "A rare change, explained",
    "after": "Want no throttling? Go fixed."
  },
  {
    "area": "Fixed-package recommendation",
    "before": "Profile changes should be uncommon. If a replacement is needed, we will explain the change and any installation or activation step.",
    "after": "Choose a fixed-data package if avoiding usage-based slowdowns is your priority. This is where we can guarantee your full purchased allowance at full available network speed."
  },
  {
    "area": "Usage introduction",
    "before": "Everyday uses need a suitable connection. We can adapt the network or, occasionally, the whole eSIM profile to help maintain service.",
    "after": "Streaming, downloads and backups can use a lot of data quickly. For guaranteed no-throttling access to your purchased allowance, choose a fixed package. Unlimited plans offer no Openline data cap, with local operator fair use still applying."
  },
  {
    "area": "Video recommendation",
    "before": "Adapt the service when needed",
    "after": "Fixed package: no usage-based slowdown"
  },
  {
    "area": "Download recommendation",
    "before": "More than one service path",
    "after": "All purchased GB at full speed"
  },
  {
    "area": "Calling recommendation",
    "before": "Connection quality matters",
    "after": "No Openline speed restriction"
  },
  {
    "area": "Backup recommendation",
    "before": "A new profile if the setup needs to change",
    "after": "Choose fixed for heavy uploads"
  },
  {
    "area": "Streaming illustration badge",
    "before": "Service that adapts",
    "after": "No Openline throttling"
  },
  {
    "area": "Service section kicker",
    "before": "Flexible Delivery",
    "after": "Choose with Confidence"
  },
  {
    "area": "Service section heading",
    "before": "Use your plan. Let the service adapt.",
    "after": "Know your plan. Know our promise."
  },
  {
    "area": "Service section introduction",
    "before": "Unlimited use does not mean one eSIM profile must stay in place forever. To maintain a good service, Openline may occasionally replace the profile and move you to a different underlying provider and connectivity setup. Some changes may need a setup step on your phone.",
    "after": "Fixed packages give you the clearest guarantee: all the data you buy, at full available network speed, without usage-based throttling. Unlimited plans have no cap or throttling added by Openline, but the local MNO may apply fair use. If that slows you down too often, we’ll try a replacement eSIM on another infrastructure with rules that better suit your location and usage."
  },
  {
    "area": "Promise checklist",
    "before": "Unlimited use on eligible unlimited plans",
    "after": "Fixed package: every purchased GB at full speed"
  },
  {
    "area": "Promise checklist",
    "before": "Network options depend on your plan and location",
    "after": "No usage-based throttling on fixed packages"
  },
  {
    "area": "Promise checklist",
    "before": "Video quality follows the available connection",
    "after": "Unlimited: no data cap added by Openline"
  },
  {
    "area": "Promise checklist",
    "before": "Alternative providers when the service needs to change",
    "after": "Unlimited: local MNO fair-use rules still apply"
  },
  {
    "area": "Promise checklist",
    "before": "Local congestion can still affect performance",
    "after": "Heavy use within 24h may trigger a slowdown"
  },
  {
    "area": "Promise checklist",
    "before": "Data for your everyday work and travel apps",
    "after": "We’ll try another infrastructure if it happens often"
  },
  {
    "area": "Promise checklist",
    "before": "Check your plan and device for hotspot support",
    "after": "Better fair use is our aim, not a guarantee"
  },
  {
    "area": "Unlimited illustration marker",
    "before": "UNLIMITED PLAN",
    "after": "LOCAL FUP MAY APPLY"
  },
  {
    "area": "Unlimited illustration badge",
    "before": "Adaptive service",
    "after": "No Openline cap"
  },
  {
    "area": "Unlimited illustration badge",
    "before": "Profile flexibility",
    "after": "Local fair use"
  },
  {
    "area": "Unlimited illustration badge",
    "before": "Network-aware",
    "after": "Support if needed"
  },
  {
    "area": "Unlimited illustration heading",
    "before": "Unlimited usage",
    "after": "Unlimited from Openline"
  },
  {
    "area": "Closing headline",
    "before": "Unlimited use, with flexibility behind it",
    "after": "Your full allowance. Our full commitment."
  },
  {
    "area": "Closing introduction",
    "before": "Choose an unlimited plan backed by the flexibility to adapt its delivery. Usually your existing profile does the job; occasionally, a replacement eSIM helps us move you to a better service setup.",
    "after": "Choose fixed data for guaranteed no-throttling access to every GB you buy. Choose unlimited for no Openline data cap, with local MNO fair-use rules still applying. If those rules limit you too often, we’ll try to find a better-fitting infrastructure for you."
  },
  {
    "area": "Closing badge",
    "before": "Profile changes may apply",
    "after": "Fixed: full-speed data"
  },
  {
    "area": "Closing badge",
    "before": "Built to adapt",
    "after": "Help with repeat slowdowns"
  },
  {
    "area": "Hero illustration",
    "before": "Download varies",
    "after": "Full-speed fixed data"
  },
  {
    "area": "Hero illustration",
    "before": "Upload varies",
    "after": "No Openline throttling"
  },
  {
    "area": "Hero illustration",
    "before": "Latency varies",
    "after": "Local rules apply"
  },
  {
    "area": "Hero illustration",
    "before": "Usage supported by profile flexibility",
    "after": "Unlimited plans: local fair use may apply"
  },
  {
    "area": "Hero usage statistic",
    "before": "Usage",
    "after": "Unlimited data"
  },
  {
    "area": "Hero guarantee statistic",
    "before": "2 · Ways to adapt",
    "after": "0 · Fixed-plan throttling"
  },
  {
    "area": "Hero allowance statistic",
    "before": "Rare · Profile changes",
    "after": "10 GB · All at full speed"
  },
  {
    "area": "Replacement section kicker",
    "before": "The flexibility behind unlimited",
    "after": "When unlimited slows you down"
  },
  {
    "area": "Replacement section heading",
    "before": "Unlimited use does not mean one profile forever.",
    "after": "Throttled too often? We’ll try another route."
  },
  {
    "area": "Replacement section introduction",
    "before": "Network selection and profile replacement are two parts of the same approach. If your current service setup is no longer a good fit, we can issue a new eSIM and move you to a different underlying provider. This should be uncommon, but it is part of the service.",
    "after": "If your unlimited plan repeatedly hits local fair-use restrictions, contact us. We’ll try to issue another eSIM profile using a different provider or infrastructure, aiming for a fair-use policy that works better in your location and for the way you use data."
  },
  {
    "area": "Network-selection distinction",
    "before": "When your current eSIM has a suitable network option, we can adapt the connection within that profile. The choices depend on your plan and location.",
    "after": "Selecting another available network keeps the current eSIM profile. It is different from moving your service to another infrastructure with a different fair-use policy."
  },
  {
    "area": "Network-selection boundary",
    "before": "Your existing eSIM profile remains in use.",
    "after": "A network change alone does not guarantee different fair-use rules."
  },
  {
    "area": "Replacement-card heading",
    "before": "A new profile.",
    "after": "Another infrastructure."
  },
  {
    "area": "Replacement-card heading",
    "before": "A different service setup.",
    "after": "A better fit, if available."
  },
  {
    "area": "Best-effort replacement promise",
    "before": "If a network change is not enough, we can issue another eSIM profile on the fly. That lets us change the underlying provider and connectivity setup, not just the network name on your screen.",
    "after": "For recurring unlimited-plan throttling, we’ll try to provide a replacement profile from another infrastructure. We hope its fair-use rules will better suit your location, environment and experience. A better result is not guaranteed."
  },
  {
    "area": "Replacement-card boundary",
    "before": "This flexibility supports both multi-network access and our unlimited-use approach.",
    "after": "A new profile changes the underlying service setup, not just the network name."
  },
  {
    "area": "Replacement disclosure heading",
    "before": "Occasionally, we may replace your eSIM profile entirely.",
    "after": "We’ll try to improve the experience. Local rules still apply."
  },
  {
    "area": "Replacement disclosure",
    "before": "It should be uncommon, but changing the whole profile is part of how we work to maintain a good service. You may need to install or enable the replacement on your phone. If a setup step is needed, we’ll guide you through it.",
    "after": "Replacement should be uncommon and depends on available alternatives. We cannot guarantee a more generous fair-use policy, faster service or no future throttling. You may need to install or enable a new profile; we’ll guide you if needed. If you want guaranteed no usage-based throttling, choose a fixed-data package instead."
  }
];
